### PR TITLE
Test branch

### PR DESCRIPTION
**Pull request by StephanieB5**
It's definitely still a work in progress but it maybe a logical place to pull code into the branch before the changes start to affect the renderers.  If nothing else the latest commit here has all the previously scattered commits squashed together.  

I'm not sure who's notified of pull requests automatically so I'm pinging the same people from the last thread: @liuxuan30, @danielgindi, @RyGuyM

Hope this helps.

### CODE REVIEW

**Comment by liuxuan30** [comment]
we will get a notification once if you watch this repo. You could squash when you reach a small milestone.

**Comment by StephanieB5** [comment]
Sounds good to me.  Thanks. :)

**Comment by RyGuyM** [comment]
@StephanieB5 thanks for the tag! I will have something you to look at in the next couple days. I've added a ChartXAxisRendererNumeric and ChartXAxisRendereTime. I've managed to extend the line and scatter charts to support proper scaling without altering too much of the source.

**Comment by StephanieB5** [comment]
Great!  I think extending the chart a few at a time is definitely the way to go.  For example, for Bar Charts it makes doesn't make sense to have both axes values represented as Doubles.  Whether in horizontal or vertical alignment, Bar charts represent data that has at least one axis with values that are discreet and equidistant.

Btw, I'm thinking regression testing: have you seen the option "Toggle auto scale min max" produce a difference in behaviour? I see in the code where _autoScaleLastLowestVisibleXIndex/_autoScaleLastHighestVisibleXIndex are set but they don't seem to be used anywhere.

I have to admit, without seeing what you've done it's hard to understand how your work fits in with mine.  Should we connect over something outside of this thread for more tight knit collaboration?

**Comment by StephanieB5** [comment]
Note: To see the "Toggle auto scale min max" scrolling is better. With "auto min max" enabled you can see the slight shift of the graph from the recalculated offset values.

**Comment by RyGuyM** [comment]
@StephanieB5 that sounds good, what is the best method for talking outside the thread for you?

**Comment by StephanieB5** [comment]
I've updated my profile to show a contact email.  Please feel free to reach me through that.  Thanks!

**Comment by StephanieB5** [comment]
Just an update: @RyGuyM has some work that he's putting the final touches on.  I'm going to wait a few days and co-ordinate with @RyGuyM about the best path forward.

**Comment by liuxuan30** [comment]
Have you considered combined chart? I don't go in details right now, but want you to know there is a combined chart might be tricky.
I got a PR #269 for grouped bars support for combined chart, not getting merged yet. If yours comes in first, I will update my PR accordingly. I am not asking that you should support grouped bars right now, but just give some thoughts about current combined chart, if it's fine, then the grouped bar support should not be hard to adopt your changes.

**Comment by StephanieB5** [comment]
Thanks for the heads up!

**Comment by danielgindi** [comment]
You might want to use [Gitter](https://gitter.im/danielgindi/ios-charts) for chatting

**Comment by StephanieB5** [comment]
@RyGuyM is putting together his work to create a pull request to resolve this issue.  I see no point in creating a competing solution for a problem. :)  I'm changing the focus of my work to give space to @RyGuyM.  I'll close this pull request but leave my branch as is to allow further development if required.

**Pull request closed without merging**
