### PR TITLE
fileprivate -> private

### PR DESCRIPTION
**Pull request by jjatie**
almsot all cases of fileprivate were meant to be private. If there is a need to use fileprivate in the future, it should be considered then. Not now.

### CODE REVIEW

**Comment by jjatie** [comment]
@liuxuan30 This is a quick and easy one.

**Comment by liuxuan30** [comment]
@danielgindi @petester42 do you remember why use `fileprivate` back then?

**Comment by liuxuan30** [comment]
when we need `fileprivate`, we could add them later.

**Comment by petester42** [comment]
Probably because private was not needed and the semantics were a little different back then.

**Pull request merged**
