### PR TITLE
[#2999]

### PR DESCRIPTION
**Pull request by jjatie**
ChartDataSet adopts conformances:
MutableCollection
RandomAccessCollection
RangeReplaceableCollection

### CODE REVIEW

**Comment by jjatie** [comment]
I entirely agree, however protocol extensions are a Swift only feature and therefor cannot be implemented on an @objc protocol. Either we get rid of objective-c, get rid of the DataSetProtocols or we accept that this is the best we can do right now.

**Comment by petester42** [comment]
If we can't do it right then I need a good reason to do it at all. Are we gonna rewrite the internal logic to use `map`, `filter` and such or it is just for the consumers of the library. I don't see much value for the consumers since they probably already do those operations to their data before creating their dataset. What use cases can you think of for needing this?

**Comment by jjatie** [comment]
That's reasonable.

Being able to take advantage of the collection conformance in the framework itself will greatly reduce the amount of code there is to maintain, unfortunately we are unable to do that in this implementation.

For consumers of the framework, the benefit they get from this is not `map`, `filter`, `reduce`, but to be able to access data in a more standard way if they need to, using subscripting, `index(where:)`, etc. That's the only justification I have for this implementation. Any future improvements to how this implemented will not change the current functionality. Because of this I think it would make sense to 
allow this change and also add it to ChartsRealm, then in the future (likely when we drop Obj-C support) we can provide a better implementation that we can take advantage of internally.

I see your argument though, and am fine if you choose to just close the PR.

**Comment by liuxuan30** [comment]
I feel dropping ObjC support is not gonna happen in near future as long as apple still use it.

**Comment by petester42** [comment]
Ya I’m leaning towards closing this PR. The only gain would be subscript access and we can just add that ourselves.

**Pull request closed without merging**
