### PR TITLE
Updated LineChart gradients (related to #3142)

### PR DESCRIPTION
**Pull request by afineon**
Made some changes to #3142 in order to make it work as it was initially implemented in #649 

screen shot 2018-03-01 at 11 24 54
screen shot 2018-03-01 at 11 25 39

I used the following code to get what is on the attached images:
```Swift
func createCharts() {
        //set x values
        let count = 10
        var xVals: [String]! = []
        for i in 0..<count
        {
            xVals.append("\(i)")
        }
        //set y values
        let range = 5.0
        var yVals: [ChartDataEntry] = []
        for i in 0..<count
        {
            let val = drand48() * range + 35
            yVals.append(ChartDataEntry(x: Double(i), y: val))
        }
        let set1 = LineChartDataSet(values: yVals, label: "DataSet 1")
        
        //Set gradient
        set1.mode = .cubicBezier
        set1.isDrawLineWithGradientEnabled = true
        chartView.drawGridBackgroundEnabled = false
        set1.lineWidth = 2.0
        set1.circleRadius = 3.0
        set1.circleHoleRadius = 1.5
        
        let colors = [UIColor.cyan, UIColor.green, UIColor.yellow, UIColor.red]
        let positions:[CGFloat] = [35.0, 36.6, 38.0, 40.0]
        
        set1.setColors(colors, alpha: 1.0)
        set1.gradientPositions = positions
        
        //axis config
        let xAxis = chartView.xAxis
        let leftAxis = chartView.leftAxis
        let rightAxis = chartView.rightAxis
        
        xAxis.drawGridLinesEnabled = false
        
        leftAxis.drawGridLinesEnabled = false
        rightAxis.drawGridLinesEnabled = false
        
        leftAxis.axisMinimum = 34.0;
        leftAxis.axisMaximum = 41.0;
        leftAxis.drawLabelsEnabled = false
        rightAxis.drawLabelsEnabled = false
        
        //limit lines
        for i in 0..<positions.count {
            let line = ChartLimitLine(limit: Double(positions[i]))
            line.label = "\(positions[i])"
            line.lineWidth = 1.0
            line.lineColor = colors[i]
            line.valueTextColor = colors[i]
            chartView.leftAxis.addLimitLine(line)
        }
    
        // set Data
        var dataSets: [LineChartDataSet] = []
        dataSets.append(set1)
        let chartData = LineChartData(dataSets: dataSets)
        chartView.data = chartData
    }
```

### CODE REVIEW

**Comment by liuxuan30** [comment]
gradient line will go into 4.0 branch. Please don't make duplicated ones. If you think yours are better than others or have enhancements, please just take @jjatie 's branch to continue.

**Comment by afineon** [comment]
@liuxuan30 sorry if I did something wrong, it's my first github commit/pull request ever. 
I'm in desperate need for line gradients in my current project and recently downloaded **draw-gradient-line** branch from main repo but noticed that gradients do not work for me as expected and I see the same result as mentioned in comments to #3142, so then I created a fork from main repo, made some changes to LineChartRenderer in **draw-gradient-line** branch to make line gradients work and decided to share the results with everyone who interested in this right now.
Could you please help me to figure out what is the best place to do that, if it's still actual - e.g. if it's already fixed in 4.0.0 then ok, I just will be using my fork in current project. 
Btw, you mentioned @jjatie 's branch, but I do not see any branches with same name "draw-gradient-line" in that fork, so I'm a bit confused.

**Comment by liuxuan30** [comment]
I understand.
I think for your best, you can just fork any branch and made the changes you need on your side, to achieve your goal or solve your problem. This is open source so you can do whatever you like.

But for merging your code into master, you need to wait until gradient line has been merged into 4.0 branch, and then you can check 4.0 branch out and add the enhancements you think it's useful for others, and we will review it.

**Comment by afineon** [comment]
Ok, I see, thanks.

**Comment by hirenkapoor7** [comment]
bro hear 

> set1.gradientPositions = positions 

this gradientPositions property cant get in Chart lib so can u plz give other solution to give gradient color in line ?

**Pull request closed without merging**
