### PR TITLE
Update library name

### PR DESCRIPTION
**Pull request by waterskier2007**
### Issue Link https://github.com/danielgindi/Charts/issues/4845

Fixes naming conflict with Apple's Charts framework

### Goals :soccer:

Update the Swift package name
Update the podspec
Update the directory structure to match
Update the Charts xcode project to use a folder-based structure instead of Groups

### Implementation Details :construction:

Implemented each step in a single commit so it's easier to follow

### CODE REVIEW

**Comment by liuxuan30** [comment]
Thanks for your contritution! this is what we exactly needed!

however, UIChart seems unpossible since it's reserved by Apple already. Would mind change to DGCharts ?

**Comment by liuxuan30** [comment]
let's make sure it biuld on xcode 14 as well

**Comment by rineek** [comment]
Shouldn't the directory names also be updated from `UICharts` to `DGCharts`?

**Comment by waterskier2007** [comment]
Wow, yep that was a big mistake on my part - updated.

**Comment by zygoat** [comment]
What about the `xcodeproj` and `podspec` filenames; wouldn't it be idiomatic for them to match the project name too?

**Comment by waterskier2007** [comment]
I am taking a look at why the snapshot test resources were removed. That was not intentional

**Comment by pmairoldi** [comment]
I am looking at this today and I do not think we need to rename all the source files. We can just change the product name. I will take some of these changes but leave the code reorg to the side. It will make maintainability easier for us to not reorg everything.

**Comment by pmairoldi** [comment]
Closed by #5027

**Pull request closed without merging**
