### PR TITLE
Removed redundant `lastHighlighted = nil`

### PR DESCRIPTION
**Pull request by jjatie**
`highlightValue` already takes care of it.

### CODE REVIEW

**Comment by liuxuan30** [comment]
I only see `highlightValues(_ highs: [Highlight]?)` nil out `lastHighlighted`, but `highlightValue` does not. 
There used to be a PR in `func clear()` specifically set `lastHighlighted` to nil because some small bugs, not cleaning `lastHighlighted` state and causes wrong highlight.
I think we need a deeper look to make sure this PR is safe.

**Comment by liuxuan30** [comment]
@jjatie where you say `lastHighlighted = nil` is handled?

**Comment by jjatie** [comment]
ChartViewBase line 483

**Comment by jjatie** [comment]
This doesn't actually solve the bug the original author intended. I feel like highlighting is messy right now, and we should reevaluate it in the future. We probably can just close this PR, but I'll let you decide.

**Comment by liuxuan30** [comment]
ah I see. right a little messy. But why put `lastHighlighted = h` outside.. 
Could we put both of them in `@objc open func highlightValue(_ highlight: Highlight?, callDelegate: Bool)`? just a quick look, not sure if any side effect..

**Comment by jjatie** [comment]
I didn't want to make the change without evaluating the impact everywhere. I'm going to close this, and reevaluate highlighting at a later time.

**Pull request closed without merging**
