### PR TITLE
Updated LineChart to Support an Array of Colors for CircleHoles - Issue #3694

### PR DESCRIPTION
**Pull request by jhatin94**
Fixes Issue #3694 

Changed the LineChartDataSet to support an array of colors for CircleHoles, similar to how CircleColors is done.

* Updated LineChartDataSet Interface to contain an array of colors for circleHoles and a function to get a circleHole color at a given index.
* Updated LineChartDataSet Implementation file to instantiate an empty NSUIColor array for circleHoleColors.
* Added implementation to get a color out of the new circleHoleColors array by index, returning the existing circleHoleColor property if the array is empty or the index is out of bounds.
* Updated the call for drawing a circleHole in the LineChartRenderer to use the new function to get the circleHoleColor by index instead of referencing the property

### Issue Link [:link:](https://github.com/danielgindi/Charts/issues/3694)
Fixes Issue #3694

### Goals :soccer:
The goal of this PR is to allow developers to customize their LineChart's individual circle holes

### Implementation Details :construction:
No new architectural changes
Now an array of circleHoleColors can be defined in the same way circleColors can be.

### CODE REVIEW

**Comment by liuxuan30** [comment]
may I ask the popularity of this? circleHoleColor is on data set basis, so each line has a consistent circleHoleColor. You want to one line have different circleHoleColor for each dot?

**Comment by jhatin94** [comment]
So in my use-case, I would like the circle hole to appear empty (i.e. white/clear) but then be filled in to the color of the line at certain data points. Thus, I need at least 2 different colors for holes. I'm not sure how popular this is, but I figured I'd add this to be totally customizable since the lines between points and the points themselves in the data set can be changed individually.

**Comment by liuxuan30** [comment]
@jjatie @petester42 what you think

**Comment by jjatie** [comment]
This is the first time I've seen this request. I worry that adding this to the library encourages things like a different hole color for every hole on a line.

**Comment by liuxuan30** [comment]
this is exactly a different hole color per hole for the same line (data set)

**Pull request closed without merging**
