### PR TITLE
remove swift-algorithms package in favor of manully importing needed …

### PR DESCRIPTION
**Pull request by pmairoldi**
Removed the need for swift-algorithms.

We were using only 2 functions so I duplicated the source code into our codebase. We now own this and do not have dependencies.

Addresses #4919 & #4938

### CODE REVIEW

**Comment by liuxuan30** [comment]
@pmairoldi, just asking, it seems builds fine, are you having problems still and have to remove the packages?

**Comment by pmairoldi** [comment]
Don't think so. I removed everything.

**Comment by liuxuan30** [comment]
what don't compile?

**Comment by pmairoldi** [comment]
Nothing but it's more to fix the Bitcode and build for distribution errors. We use only 2 functions. I'd rather own the code than have a dependency for such a small thing.

**Pull request merged**
