### PR TITLE
All Charts Icons Support [Dub #629, #624]

### PR DESCRIPTION
**Pull request by abjurato**
Finally, implemented Icons (Nodal Image) feature for all charts.

simulator screen shot 22 jul 2016 9 03 19 pm simulator screen shot 22 jul 2016 9 04 04 pm

I've chosen to store image in data parameter of ChartDataEntry to allow icons to be specified per-value (example of use: to sign personal records in running application). Dataset can specify if it will draw icons and customise offset from default placement. IconOffset is CGSize, but for radial Radar and Pie only height value matters — as distance from centre.

ChartBaseDataSet, IChartDataSet: 
1. drawIconsEnabled:Bool flag and isDrawIconsEnabled() accessor for it
2. iconsOffset:CGSize which allows to influence at placement of icon on chart in relation to value's text (wether it is visible or not)

ChartUtils:
1. drawImage(context:CGContext, image:NSUIImage, point:CGPoint, expectedSize:CGSize, offset:CGSize) - draws image in context

All xxxChartRenderers:
1. code to draw icon (if data set's isDrawIconsEnabled and image is included to entry's data) in drawValues() method

BarChartDataEntry:
1. initialiser for stacked bar with data parameter — one data for whole stack

Demos: included star image to project, for stacked bar, pie, scatter, radar, line, candle stick, bubble, bar and horizontal bar added Toggle Icon button and star to be drawn.

### CODE REVIEW

**Comment by liuxuan30** [comment]
could you please squash the commits to more compact?

**Comment by liuxuan30** [comment]
also, does this mean we can close #624, #629?

**Comment by AnatolyRosencrantz** [comment]
@liuxuan30 thanks! squashed. Yes, all effects of #624 and #629 can be achieved using this branch. Will wait and hope there will not be too many conflicts with 3.0 release.

Btw, will version 3.0 be written on Swift3?

**Comment by liuxuan30** [comment]
@AnatolyRosencrantz thanks for the effort. 
I think it depends on when @danielgindi will finish the work. If Charts 3.0 comes after swift 3 release, it will be converted into swift 3.0 I suppose. The current swift-3.0 branch is just a temp branch I guess in order to test iOS 10. It's much easier to convert all in once than continuous converting... every beta has swift changes is annoying

**Comment by liuxuan30** [comment]
BTW, did you include the unit tests?

**Comment by AnatolyRosencrantz** [comment]
@liuxuan30 nope. Should I update BarChartTests and LineChartTests or something more complex?

**Comment by liuxuan30** [comment]
@AnatolyRosencrantz it's great that you could add the tests for icons, just have some samples to test is enough? Take your time, it's nice to have but not forcing

**Comment by AnatolyRosencrantz** [comment]
@liuxuan30 updated existing BarChartTests and LineChartTests

**Comment by liuxuan30** [comment]
@AnatolyRosencrantz great work! Thanks so much

**Comment by michaeljules** [comment]
Is there a way to add different icons for each bar?

**Comment by AnatolyRosencrantz** [comment]
@michaeljules yes, icon is being set per-DataEntry (bar in BarChart or point in LineChart), in it's data property. This property is optional, so if no UIImage will be included or some other object will be found there — icon for that exact DataEntry will just not be drawn.

**Comment by liuxuan30** [comment]
@AnatolyRosencrantz just FYI, Daniel wants to release v3 first and review and merge this after v3

**Comment by Anders123fr** [comment]
Can this be merged now with the release of 3.0?

**Comment by abjurato** [comment]
Pull Request for Swift3 — #1793

**Comment by kiroskirin** [comment]
@abjurato Is it possible to show icons only for highlight values?

**Comment by timotiuserick** [comment]
Can it support gif ? Really love this feature

**Pull request closed without merging**
