### PR TITLE
Changes for Swift 4.2, Xcode 10 and iOS 12

### PR DESCRIPTION
**Pull request by jlcanale**
### Issue Link :link:
Apple renamed keys and functions in Swift 4.2

### Goals :soccer:
Get a branch started to use these changes during the beta period.

Please merge into a new branch Swift-4.2

### CODE REVIEW

**Comment by jlcanale** [comment]
Sounds good, I'll use my fork until then.

**Comment by liuxuan30** [comment]
@jjatie take your time. I could also take care of Swift 4.2 upgrade. If we cannot make it before Swift 4.2, let's merge into master first and handle our refactoring then.

>Some of my bigger changes

Are these bigger changes in `target for 4.0` card, or in `in progress`? There are only two PRs left in `in progress`: #3164 and #3187.

**Comment by jjatie** [comment]
@liuxuan30 They aren't on the task board at all. I don't have time to work on them, so there's no point in talking about them now.

@petester42 From Xcode 10 beta 5 notes:
> Various CoreGraphics calls have been hardened against continuing with invalid parameters. In iOS 12 beta, these calls may now return NULL or return early. (38344690)

**Comment by petester42** [comment]
I don’t see where we would be passing invalid parameters.

**Comment by Witzeneder** [comment]
Is there any update on this matter?

**Comment by petester42** [comment]
Xcode 10 hasn’t been released yet so no

**Comment by jlaws** [comment]
As @kabouzeid said, the GM is out and we can start submitting apps using the latest version of XCode.  Would be great to get this merged!

**Comment by jjatie** [comment]
@liuxuan30 @petester42 I have a little time today. Would you like me to get the pod Xcode 10/Swift 4.2 ready? Alternatively, we can do this just for the 4.0.0 branch?

**Comment by petester42** [comment]
I don’t think 4.0.0 is ready. Do it on master

**Comment by petester42** [comment]
thanks

**Comment by liuxuan30** [comment]
cheers guys. My laptop is broken... took sometime to restore everything

**Comment by petester42** [comment]
I’m finishing things off. Release tonight or tomorrow

**Comment by liuxuan30** [comment]
sure, thanks a lot

**Comment by jlaws** [comment]
Works great, thank you!

**Pull request merged**
