### PR TITLE
Removed `isKind(of:)`

### PR DESCRIPTION
**Pull request by jjatie**
in favour of the Swift `is`

### CODE REVIEW

**Comment by jjatie** [comment]
The uses of `isKind(of:)` in the equality methods are taken care of in #3002

**Comment by jjatie** [comment]
@liuxuan30 This is a quick and easy one.

**Comment by liuxuan30** [comment]
sorry, had a busy week. I will try finish some

**Comment by liuxuan30** [comment]
info: https://stackoverflow.com/questions/24877661/is-there-a-difference-between-is-and-iskindofclass
https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/TypeCasting.html#//apple_ref/doc/uid/TP40014097-CH22

**Pull request merged**
