### PR TITLE
Fix decimals crash in ChartsUtil

### LINKED ISSUE #1550: fatal error: Double value cannot be converted to Int because it is either infinite or NaN
When I use LineChart APIs, I am getting fatal error at ChartUtils.swift @ line 53.

`fatal error: Double value cannot be converted to Int because it is either infinite or NaN`

```
    internal class func decimals(_ number: Double) -> Int
    {
        if number.isNaN || number.isInfinite || number == 0.0
        {
            return 0
        }
        
        let i = roundToNextSignificant(number: Double(number))
        **return Int(ceil(-log10(i))) + 2**
    }
```

### PR DESCRIPTION
**Pull request by petester42**
Closes #1550, #1540, #1491

I added some tests based on the crash mentioned in #1550 and there was a crash when using DBL_MAX as the input of the `decimals` function. 

There are still some abnormalities in the `decimals` function I believe. In MPAndroidCharts I ran the same tests and it returns 2 not zero for all these cases except for the ones that crash and return negative Int max.

This pull request fixes the crash but I don't think the `decimals` function does what we want it to do.

@danielgindi, @PhilJay what is this function actually supposed to do?

### CODE REVIEW

**Comment by danielgindi** [comment]
It's supposed to calculate a default number of decimals to show after the decimal point

**Comment by danielgindi** [comment]
It's not really important what the value is on edge cases. It is used as a default for formatters that were not configured by the user, it just shouldn't crash :-)

**Comment by petester42** [comment]
The main reason I was asking what it does is that I believe it does not do what it's supposed to. See the `testDecimalWithNormalValue` test case. Shouldn't it return 6? If not then why are we doing some complex math if it can only be 0 or 1.

**Comment by umairnow** [comment]
This issue is still there in AxisRendererBase.swift on line 125
fatal error: Double value cannot be converted to Int because it is either infinite or NaN

**Comment by acegreen** [comment]
@petester42 @danielgindi this isn't resolved yet.. 

```
        let yRangeBuffer: Double = 50000
        lineChartView.xAxis.axisMinimum = set1.yMin - yRangeBuffer
        lineChartView.xAxis.axisMaximum = set1.yMax + yRangeBuffer
```

**Comment by danielgindi** [comment]
Guys, the reason that this is not fixed, is that we do not see this error.
So you would have to:

1. Make sure you are doing everything correctly
2. Create steps for us to reproduce
3. Maybe do a little debugging. Why does a `NaN` or `Infinity` get passed to that function?

**Pull request merged**
