### PR TITLE
BarLineChart - add a flag to cancel highlights when the drag gesture ends

### PR DESCRIPTION
**Pull request by andrewloyola**
This pull request adds the option (disabled by default) to clear highlights when a drag gesture ends on BarLineChartView.  When enabled, highlighting acts like a momentary switch, where highlights appear only when the user is dragging.

### CODE REVIEW

**Comment by liuxuan30** [comment]
just wondering if the variable name could be a little shorter lol

**Comment by liuxuan30** [comment]
@andrewloyola seems you made a mistake? You merged swift 2.3 while this PR is for master.
Also, please consider squash the commits

**Comment by andrewloyola** [comment]
Good point, @liuxuan30 I forgot about this PR since it was a few months ago, I'll have to cancel and resubmit it

**Comment by liuxuan30** [comment]
@andrewloyola actually you don't have too - you just have to rebase this branch and force push

**Pull request closed without merging**
