### PR TITLE
Swift iOS Demos

### PR DESCRIPTION
**Pull request by jjatie**
Added Swift version of all the iOS demos.

### CODE REVIEW

**Comment by jjatie** [comment]
This pull request is purely additive and does not change anything in the framework. It's very easily testable and is a great resource for the many iOS developers who never learned Objective-C.

**Comment by liuxuan30** [comment]
Thanks! It might some time to review and get merged. Quite short handed :(

**Comment by jjatie** [comment]
Don't know why I didn't do that in the first place, but it's now one project with 2 targets

**Comment by jjatie** [comment]
@petester42 Your requested changes have been made.

**Comment by petester42** [comment]
I’ll review this later tonight or tomorrow. Fairly straightforward. Should be good to go.

**Comment by liuxuan30** [comment]
gees, can someone stop @jjatie sending PRs lol. I saw dozens of PRs when I just wake up.

**Pull request merged**
