### PR TITLE
Add a gradient line chart

### PR DESCRIPTION
**Pull request by Regno**
For [#537](https://github.com/danielgindi/ios-charts/issues/537)
Add functionality to draw a gradient line for line chart. It use exist property "colors" and new property "gradientPositions" for rendering gradient line.
Add two new public properties: "gradientPositions" and "drawGradientEnabled" for LineChartDataSet.
Add two new private functions: "drawGradientLine" and "generatePath" for LineChartRenderer

Example of usage:

``` swift
override func viewDidLoad() {
        super.viewDidLoad()
        //set x values
        let count = 10
        var xVals: [String]! = []
        for (var i = 0; i < count; i++)
            {
                xVals.append("\(i)")
            }
        //set y values
        let range = 5.0
        var yVals: [ChartDataEntry] = []
        for (var i = 0; i < count; i++)
            {
                let val = drand48() * range + 35
                yVals.append(ChartDataEntry(value: val, xIndex: i))
            }
        let set1 = LineChartDataSet(yVals: yVals, label: "DataSet 1")
        //Set gradient
        set1.drawCubicEnabled = true
        set1.drawGradientEnabled = true
        chartView.drawGridBackgroundEnabled = false
        //set1.drawFilledEnabled = true
        set1.lineWidth = 2.0
        set1.circleRadius = 2.0
        set1.colors = [UIColor(red: 0.192, green: 0.686, blue: 0.980, alpha: 1.00), UIColor(red: 0.212, green: 0.863, blue: 0.318, alpha: 1.00), UIColor(red: 0.996, green: 0.867, blue: 0.275, alpha: 1.00), UIColor(red: 0.980, green: 0.090, blue: 0.157, alpha: 1.00)]
        set1.gradientPositions = [35.0, 36.6, 38.0, 40.0]
        // set Data
        var dataSets: [LineChartDataSet] = []
        dataSets.append(set1)
        let chartData = LineChartData(xVals: xVals, dataSets: dataSets)
        chartView.data = chartData
}
```

Result:

### CODE REVIEW

**Comment by petester42** [comment]
cool! there are conflicts with master could you rebase to fix those?

**Comment by Regno** [comment]
Done.

**Comment by maciejtrybilo** [comment]
It's precisely what I need. Could I help at all moving this PR forward?

**Comment by liuxuan30** [comment]
awesome!

**Comment by nehayward** [comment]
Any update on when this will get merged?

**Comment by danielgindi** [comment]
When it will be ready for merging.
Right now it is marked with "code styling problems", and it is already too far behind (merge conflicts).
When this PR will be ready, we'll need to implement the Android counterpart, but let's get at it one step at a time

**Comment by tnmendes** [comment]
Hi, any update about this feature? thank you

**Comment by NeelAppsplanet** [comment]
hi @Regno nice work , any update about this feature from your side? currently i'm working on swift 3.1 and getting some issues while migrating code from swift 2.1 , It would b great if you help me to get out. Have u migrate this code repo. in swift 3.1 ?

**Comment by thomashempel** [comment]
Is there any chance this is gonna be merged anytime soon? I'd like to avoid forking the pod.

**Comment by Kalvin126** [comment]
Any update on this? Would be nice to pull into main repo

**Comment by mdnjustin** [comment]
This is what I've been looking for. Would love for it to make it into the main branch.

**Comment by robin-garnham** [comment]
Will this also work for fixed stop colours?
I'm trying to implement a line chart that is differently coloured based on Y position.
E.g. gray at 0 -> 34.99, green at 35.00 -> 49.99, etc

**Comment by NallapatiMalleswari** [comment]
How to draw Gradient line based on width like in bellow image,but not based on x-axis ,y-axis based.
screen shot 2017-10-28 at 6 27 05 pm

**Comment by liuxuan30** [comment]
seems not updated to swift 4. @danielgindi This feature has been asked a lot. Shall we go ahead without android support? I think we need a plan for new features that does not sync between iOS and android. waiting for the other one seems will take too long

**Comment by gunesmert** [comment]
Hey @liuxuan30 & @danielgindi . Is there any estimated time of merging this PR?

**Comment by dhaneshgosai** [comment]
Hey @danielgindi @liuxuan30 

Any update when can we expect this feature on master branch ?

Thanks!

**Comment by jlubeck** [comment]
Almost 2 years since this very nice pull request. Just wondering, is anyone workin on fixing the merge conflicts?
Thanks!

**Comment by petester42** [comment]
I started looking at gradient stuff a while back and haven’t had to time to look through the code and merge/close all issues related to it.

From what I remember the timing of this pull request was not ideal since it was in the middle of the refactor from charts v2 to v3. That is why it has taken more time for it to make it in since basically all the code would have to be rewritten in the v3 style.

**Comment by liuxuan30** [comment]
There are several projects on github page created and now ongoing as high priority, and this is one of them. I think once we finish the 'more swift' project, we will focus on gradient and the named axis

**Comment by AndreaMiotto** [comment]
Can you merge this pull request?

**Comment by jjatie** [comment]
First there needs to be no merge conflicts. @liuxuan30, I think other features can be added while the "More Swift" project is ongoing. If there are any PRs you're uncertain match the Swift-ier style, feel free to tag me. If this is the gradient implementation we are going to go with, we should prioritize it.

I think we have an issue with the `Fill` type. As it is, users cannot extended it with different types without changing the framework source. I will create an issue about this.

**Comment by liuxuan30** [comment]
a long time ago, this PR is almost accepted, except for the code style problems, and then we are uncertain whether to go ahead without porting to android side, so many feature PRs are on hold since then. And Swift 3.0/4.0 kicks in, so more conflicts for this.

I think the implementation is accepted, so the next work is we reimplement this on your refactoring base and get it merged, as what I planned.

For the `Fill` part, this is something I am concerned since you would have different opinion, before we simply solve the conflict and merge.

**Comment by jjatie** [comment]
@liuxuan30 Would you like me to reimplement this in a clean branch so that we can get this merged?

**Comment by liuxuan30** [comment]
I would suggest you take some rest :) You already did a lot.

**Comment by jjatie** [comment]
@liuxuan30 I'm updating this so it can be merged today. Do we want it for 3.x or 4.0.0?

**Comment by jjatie** [comment]
Made current in #3141.

**Comment by HebeTienCoder** [comment]
Hi, any updates on this? Do you have any idea when this feature will be available? Also, do you think the corresponding branch could be stable enough to use in an app? Thanks!

**Comment by Kalvin126** [comment]
guys... https://github.com/danielgindi/Charts/pull/3415 was merged and will be in version `4.0.0` which is not yet out.

**Comment by girishk55** [comment]
When we can expect to get the line gradient chart feature in Chart-iOS (version 4.0.0). As mentioned "guys... #3415 was merged and will be in version 4.0.0 which is not yet out."

**Comment by Jartz** [comment]
i use.
pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => '4.0.0'


`

    func setDataCount(values: [ChartDataEntry]?) {
        
        let set1 = LineChartDataSet(values: values!, label: "DataSet 1")

        chartView.drawGridBackgroundEnabled = false

        set1.setColors(UIColor.init(red: 249/255, green: 192/255, blue: 45/255, alpha: 1), UIColor.init(red: 216/255, green: 36/255, blue: 38/255, alpha: 1))
        set1.isDrawLineWithGradientEnabled = true
        set1.gradientPositions = [0, 130]


        set1.lineWidth = 1.0
        set1.circleRadius = 3.0
        set1.fillAlpha = 1.0
        set1.drawFilledEnabled = true

        set1.drawCircleHoleEnabled = false
        set1.valueFont = .systemFont(ofSize: 9)
        set1.formLineDashLengths = [5, 2.5]
        set1.formLineWidth = 3
        set1.formSize = 15


        let iconRect = set1.iconsOffset
        set1.iconsOffset = CGPoint(x: iconRect.x + 8, y: iconRect.y)

        set1.drawFilledEnabled  = false
        set1.drawCirclesEnabled = false
        set1.drawIconsEnabled   = true
        set1.drawValuesEnabled  = false


        let data = LineChartData(dataSet: set1)
        chartView.data = data
    }
`


Captura de pantalla 2019-03-27 a la(s) 1 39 36 p  m  (2)

**Comment by truongtantri** [comment]
The graph draw incorrect(I make the red circle in the attachment)

Data for draw graph:
- gradientPositions = (10, 9, 7, 7, 7, 7, 7, 7, 6, 7, 11, 16, 22, 26, 34, 36, 49, 49, 48, 46, 45, 44, 48, 43, 49, 48, 68, 64, 62, 58, 65, 65, 35, 30, 32, 31, 58, 42, 33, 33, 35).

graph

Is it a bug of lib? please help me fix it. Thanks.

**Comment by StrauneanuDimitri** [comment]
@truongtantri - How did you get the chart to draw those gradient lines?

**Comment by truongtantri** [comment]
@StrauneanuDimitri
pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => '4.0.0'

and data points in my post.

**Pull request closed without merging**
