### PR TITLE
Make legendRenderer property public in order to be externally customizable

### PR DESCRIPTION
**Pull request by nagykatalin**
### Goals :soccer:
The main idea behind this pull request is to make the legend renderer externally customizable and overridable.

Our customer's request was to detect when the user's clicks on a legend and to highlight corresponding line on the chart.

### Implementation Details :construction:
By making public the legendRenderer property (similarly to the renderer property) we would like to use our own legend renderer class which stores the exact location of the labels and in this way we can detect if the user clicked on a label or not.

### CODE REVIEW

**Comment by jjatie** [comment]
@nagykatalin I'm okay with this, however please target 4.0.0 instead of master.
@liuxuan30 Any comments?

**Comment by liuxuan30** [comment]
I'm ok too, giving the fact other major renderers are already public. But I recommend be careful about the parameters, as ` LegendRenderer(viewPortHandler: _viewPortHandler, legend: _legend)`,  `viewPortHandler` may not be available outside.

**Comment by petester42** [comment]
I think legend still being readonly is fine.

**Comment by petester42** [comment]
Thanks 👍

**Comment by liuxuan30** [comment]
good to have you back:)

**Pull request merged**
