### PR TITLE
Fix memory leak after rendering

### PR DESCRIPTION
**Pull request by YusukeOba**
### Issue Link :link:

#3671
#3649

### Goals :soccer:

No memory leak.

### Implementation Details :construction:

* Added weak modifier to NSUIAccessibilityElement#container.
* Added guard statements.

### Testing Details :mag:

I tested in example demo and my project.

### CODE REVIEW

**Comment by YusukeOba** [comment]
@liuxuan30
@petester42

Would you be able to review this source code?

I think there is a problem of cyclic reference by #1060.

# Example in LineChartRenderer.

1. Create and hold NSUIAccessibilityElement. depends on ChartView.
https://github.com/danielgindi/Charts/blob/master/Source/Charts/Renderers/LineChartRenderer.swift#L621

2. NSUIAccessibilityElement strong reference on ChartView.
https://github.com/danielgindi/Charts/blob/98a472cf77a419e63a5a853b04515cb3d4f34079/Source/Charts/Utils/Platform%2BAccessibility.swift#L107

**Comment by petester42** [comment]
I’ll look at it sometime this weak

**Comment by YusukeOba** [comment]
Sorry about that. I fixed for macOS. 😃

**Comment by petester42** [comment]
Thanks

**Comment by YusukeOba** [comment]
Thank you for your time. 😄

**Pull request merged**
