### PR TITLE
[WIP] Release/5.0.0

### PR DESCRIPTION
**Pull request by pmairoldi**
Work to release a 5.0 version of Charts. The main goal of the release is to rename the library to DGCharts.

### CODE REVIEW

**Comment by liuxuan30** [comment]
tried ChartsDemo-iOS, not build when BUILD_LIBRARY_FOR_DISTRIBUTION is on
I have filed a post https://forums.swift.org/t/bug-report-unable-to-build-demo-project-if-imported-swift-framework-turned-on-build-library-for-distribution/63904

**Comment by liuxuan30** [comment]
btw, have you tried running the tests, should we update the test images using new Xcode?
Previously I ran into failures because the UIKit update something and the images had like 0.1% or 1% diff, mostly like the font is a little bit bolder or slightly position shift.

**Comment by pmairoldi** [comment]
> tried ChartsDemo-iOS, not build when BUILD_LIBRARY_FOR_DISTRIBUTION is on
> I have filed a post https://forums.swift.org/t/bug-report-unable-to-build-demo-project-if-imported-swift-framework-turned-on-build-library-for-distribution/63904

Yeah this is the issue I ran into as well.

**Comment by pmairoldi** [comment]
> btw, have you tried running the tests, should we update the test images using new Xcode?
> Previously I ran into failures because the UIKit update something and the images had like 0.1% or 1% diff, mostly like the font is a little bit bolder or slightly position shift.

Hmm yeah I don’t know. The test run fine on CI but it might be a good idea. Could you add an issue to the 5.0 milestone so we don’t forget.

**Comment by liuxuan30** [comment]
> > btw, have you tried running the tests, should we update the test images using new Xcode?
> > Previously I ran into failures because the UIKit update something and the images had like 0.1% or 1% diff, mostly like the font is a little bit bolder or slightly position shift.
> 
> Hmm yeah I don’t know. The test run fine on CI but it might be a good idea. Could you add an issue to the 5.0 milestone so we don’t forget.

https://github.com/danielgindi/Charts/issues/5033. The forum not responding, I will file a radar then.

**Comment by rineek** [comment]
> On my mac it is
> 
> ```
>  Executed 66 tests, with 52 failures (0 unexpected) in 12.944 (13.016) seconds
> Program ended with exit code: 1, 
> ```
> 
> Xcode Version 14.2 (14C18), 14 Pro Simulator 16.2.
> 
> **Compared two diffs, mostly the label diff, the issue is the label I generated is grey, while the test image is black** It's weird I thouched nothing and the color has huge difference. I didn't specify grey.
> 
> image image

_Toggle Appearance_ option for iOS simulator changes test results:
_Dark_:
Screenshot 2023-03-29 at 19 08 23
_Light_:
Screenshot 2023-03-29 at 19 09 43
Xcode 14.2 (14C18), 14 Pro Simulator 16.2

**Comment by liuxuan30** [comment]
> tried ChartsDemo-iOS, not build when BUILD_LIBRARY_FOR_DISTRIBUTION is on I have filed a post https://forums.swift.org/t/bug-report-unable-to-build-demo-project-if-imported-swift-framework-turned-on-build-library-for-distribution/63904
> 
> radar: https://feedbackassistant.apple.com/feedback/12078082

I didn't get any reply from Swift forum nor radar. Not sure what we should go for, either wait or make a release but pointing out the Objc'demo is broken

**Comment by liuxuan30** [comment]
> > On my mac it is
> > ```
> >  Executed 66 tests, with 52 failures (0 unexpected) in 12.944 (13.016) seconds
> > Program ended with exit code: 1, 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Xcode Version 14.2 (14C18), 14 Pro Simulator 16.2.
> > **Compared two diffs, mostly the label diff, the issue is the label I generated is grey, while the test image is black** It's weird I thouched nothing and the color has huge difference. I didn't specify grey.
> > image image
> 
> _Toggle Appearance_ option for iOS simulator changes test results: _Dark_: Screenshot 2023-03-29 at 19 08 23 _Light_: Screenshot 2023-03-29 at 19 09 43 Xcode 14.2 (14C18), 14 Pro Simulator 16.2

it shouldn't bother? or the dark mode changed the label color or background color? Normally we don't care dark or not. Just make sure the chart positions itself correctly.

**Comment by rineek** [comment]
> > > On my mac it is
> > > ```
> > >  Executed 66 tests, with 52 failures (0 unexpected) in 12.944 (13.016) seconds
> > > Program ended with exit code: 1, 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Xcode Version 14.2 (14C18), 14 Pro Simulator 16.2.
> > > **Compared two diffs, mostly the label diff, the issue is the label I generated is grey, while the test image is black** It's weird I thouched nothing and the color has huge difference. I didn't specify grey.
> > > image image
> > 
> > 
> > _Toggle Appearance_ option for iOS simulator changes test results: _Dark_: Screenshot 2023-03-29 at 19 08 23 _Light_: Screenshot 2023-03-29 at 19 09 43 Xcode 14.2 (14C18), 14 Pro Simulator 16.2
> 
> it shouldn't bother? or the dark mode changed the label color or background color? Normally we don't care dark or not. Just make sure the chart positions itself correctly.

In dark mode where only BarChartTests failed, simulator labels' colors were white, but chart positions remained the same:
Screenshot 2023-04-12 at 15 37 51
Snapshot images for Logical width 393 and Logical height 852(e.g. iPhone 14 Pro) have different label colors for different chart types:
Screenshot 2023-04-12 at 15 48 56
Screenshot 2023-04-12 at 15 49 04
If I update BarChartTests for that logical size with white label snapshots then all tests pass:
Screenshot 2023-04-12 at 16 12 48

**Comment by liuxuan30** [comment]
@rineek usually we don't care too much about dark mode tests.

**Comment by FelixHerrmann** [comment]
> tried ChartsDemo-iOS, not build when BUILD_LIBRARY_FOR_DISTRIBUTION is on I have filed a post https://forums.swift.org/t/bug-report-unable-to-build-demo-project-if-imported-swift-framework-turned-on-build-library-for-distribution/63904
> 
> radar: https://feedbackassistant.apple.com/feedback/12078082

Hey guys, bumping the minimum iOS version to iOS 13 resolves the issue. I've actually created a fresh Objective-C project, added the binary framework, created the Swift files to use the marker subclasses and as soon as I lowered the minimum deployment target to < 13.0 the build error appear. Hope that helps and we can get a release soon.

**Comment by FelixHerrmann** [comment]
Also, can we add #5041 and #5043 to this release? That would be awesome!

**Comment by pmairoldi** [comment]
@FelixHerrmann thanks. Will look at all that maybe this weekend.

**Comment by waterskier2007** [comment]
@pmairoldi do you think it's reasonable to bump the minimum version as @FelixHerrmann mentioned?

**Comment by waterskier2007** [comment]
@pmairoldi  is there any way I could assist in this. Is a new PR required just to bump the min version and test?

**Comment by waterskier2007** [comment]
https://github.com/danielgindi/Charts/pull/5062

**Comment by waterskier2007** [comment]
@pmairoldi any update on when we might be able to get a release?

**Comment by liuxuan30** [comment]
so, seems good to go? will try to compare the light mode tests, if it's just slight mis positioning, I can update the tests and merge.

**Comment by pmairoldi** [comment]
There are a couple points left in milestone 5.0.0

**Comment by liuxuan30** [comment]
eh. I will see what I could take on tomorrow

**Comment by pmairoldi** [comment]
5.0.0 has been released.

**Comment by liuxuan30** [comment]
cheers, maybe get a beer from the funds!

**Pull request merged**
