### PR TITLE
Bar and Pie Chart Icons [Dup #629?]

### PR DESCRIPTION
**Pull request by zmchristensen**
Bar and Pie Charts now support icons.

Added ability to draw icons on Bar and Pie charts when an image name is specified in ChartDataEntry.data. Added Boolean flags 'isDrawIconEnabled`and`isDrawIconAboveBarEnabled` (similar to the existing drawValues logic). Icon size is dependent on bar width or size of pie slice.

### CODE REVIEW

**Comment by liuxuan30** [comment]
what is these icons? Do you have a screenshot?

**Comment by zmchristensen** [comment]
Here's some screenshots from the demo app:

simulator screen shot dec 24 2015 8 14 33 am
simulator screen shot dec 24 2015 8 14 14 am
simulator screen shot dec 24 2015 8 13 57 am

**Comment by gal-orlanczyk** [comment]
Any news about this feature?

**Comment by danielgindi** [comment]
I'm waiting for Phil to finish his work on the new flexible x-indices system, and then we'll get back to this one

**Comment by Anders123fr** [comment]
Looking forward to this!

**Comment by sashalondon** [comment]
This is exactly what I need to be able to make this chart:
plop_ui_wireframe_2_copy_sketch

Any news when this might be ready?

**Comment by abjurato** [comment]
#1261

**Pull request closed without merging**
