### PR TITLE
Added value text rotation

### PR DESCRIPTION
**Pull request by chinh-tran**
I've implemented the option to rotate value texts, which looks like below:
charts-rotated

**Usage**:
```swift
let ds = LineChartDataSet(values: yse1, label: "Hello")
ds.valueRotationAngle = 270.0
```
    

There is a new attribute in `IChartDataSet`:
```swift
var valueRotationAngle: CGFloat { get set }
```
and `ChartBaseDataSet`: 
```swift
open var valueRotationAngle: CGFloat = CGFloat(0.0)
```
In order to rotate the values, I'm reusing the drawText function in ChartUtils, which is already being used to rotate the labels:
```swift
open func drawText(_ text: String, at point: CGPoint, anchor: CGPoint, angleRadians: CGFloat, attributes: [NSAttributedStringKey : Any]?)
```

### CODE REVIEW

**Comment by jjatie** [comment]
@chinh-tran are you able to rebase on master?

**Comment by chinh-tran** [comment]
@jjatie yes, rebase done :)

**Comment by liuxuan30** [comment]
if this is a good feature to have, let's target 4.0?

**Comment by jjatie** [comment]
I think this is good for 4.0
@chinh-tran Thank you for your work. I'm sorry to ask this of you again, but can you please rebase on 4.0.0 and change the PR target to 4.0.0?
We can merge it in right away then and you won't have to keep updating the PR.

**Comment by chinh-tran** [comment]
Alright, I replayed the changes onto 4.0.0.

**Comment by jjatie** [comment]
Ah! Sorry, I thought I had submitted this review ages ago. @chinh-tran please take a look

**Comment by chinh-tran** [comment]
@jjatie It's updated now, however the CI build is failing but it's not related to this PR I guess.

**Comment by jjatie** [comment]
No, it’s my fault. I moved 4.0.0 to swift 4.1 and forgot to update the Travis script. It’s done in a different branch atm, but @liuxuan30 is busy this week. I’ll let you know when it’s merged.

**Comment by liuxuan30** [comment]
@jjatie I'm seeing many PRs you updated and many conflicts. Is this caused by new commits on 4.0 branch?

**Comment by jjatie** [comment]
@liuxuan30 4.0.0 is updated for Swift 4.1, but I forgot to update the travis ci file. It's updated in the top ticket in the 4.0 project, so when that's merged everything will be good to go again.

**Comment by liuxuan30** [comment]
Can you send me the link. I didn't see a similar one neither in More Swift nor 4.0 project

**Comment by yuldong** [comment]
would love to see in this feature in master，is there any plan on master to archive this?

**Pull request merged**
