### PR TITLE
Add Swift Package Manager support.

### PR DESCRIPTION
**Pull request by BrianDoig**
This implements https://github.com/danielgindi/Charts/issues/753 by adding a Package.swift file.

### CODE REVIEW

**Comment by liuxuan30** [comment]
Just curious, swift pkg mgr does not need the library version? How do we update? (new to swift pkg, but will spend some time on it later)

**Comment by liuxuan30** [comment]
seems fine. @petester42 or swift experts?

**Comment by doofyus** [comment]
Could this please be merged in.

**Comment by liuxuan30** [comment]
I will merge.

**Comment by danielgindi** [comment]
Cool :-)

**Comment by petester42** [comment]
What about the dependency on UIKit/AppKit? Is there a way to identify that this will only work on Mac and if you have the sdk installed?

**Comment by petester42** [comment]
@doofyus could you elaborate what you needed this for? I was asked a question about spm support and from what I know about spm it can’t be used with apps right now.

**Comment by doofyus** [comment]
It's true that SPM is a bit limited currently, but it can be used to keep the _dependencies_ up to date and with some workarounds, it's possible to use them in an app as well (i use SPM in a couple of them).

**Pull request merged**
