### PR TITLE
LineChart: drawing image on nodal points [Dup #624?]

### PR DESCRIPTION
**Pull request by AnatolyRosencrantz**
Sometimes circle in the nodal point is not enough customisation. Here implemented add-on to LineChart renderer which allows to draw custom UIImage instead of (or on top of) circle.

For using: switch DataSet.drawNodalImageEnabled=true, set image by DataSet.nodalImage=UIImage() and that's it. See demo project also.

### CODE REVIEW

**Comment by danielgindi** [comment]
It seems like both you and @zmchristensen are trying to implement icons, for different charts.
But the code differs a lot - and we would want a unified way of doing that across all charts.
Is there a chance that you guys will do some more work on merging those two?

**Comment by zmchristensen** [comment]
@danielgindi: between the two implementations, do you have a preference for how icon are drawn?

**Comment by danielgindi** [comment]
Not really- it just needs to be consistent as much as it can be with other APIs in the framework

**Comment by AnatolyRosencrantz** [comment]
@zmchristensen finally I've got time to fix this issue. Which of your branches can I merge my changes with? master or chart-icons?

**Comment by zmchristensen** [comment]
The chart-icons branch will be best.

**Comment by abjurato** [comment]
Feature of this PR is included in #1261

**Pull request closed without merging**
