### PR TITLE
All Charts Icons Support Swift3 [Dub #629, #624, #1261]

### PR DESCRIPTION
**Pull request by abjurato**
Finally, implemented Icons (Nodal Image) feature for all charts and updated to Swift3.
6ff3141e-5050-11e6-92e4-a3ccef6b1eaa6be3a3b6-5050-11e6-9eb5-48cb1cbac3ac
I've chosen to store image in data parameter of ChartDataEntry to allow icons to be specified per-value (example of use: to sign personal records in running application). Dataset can specify if it will draw icons and customise offset from default placement. IconOffset is CGSize, but for radial Radar and Pie only height value matters — as distance from centre.

ChartBaseDataSet, IChartDataSet:
1. drawIconsEnabled:Bool flag and isDrawIconsEnabled() accessor for it
2. iconsOffset:CGSize which allows to influence at placement of icon on chart in relation to value's text (wether it is visible or not)

ChartUtils:
1. drawImage(context:CGContext, image:NSUIImage, point:CGPoint, expectedSize:CGSize, offset:CGSize) - draws image in context

All xxxChartRenderers:
1. code to draw icon (if data set's isDrawIconsEnabled and image is included to entry's data) in drawValues() method

BarChartDataEntry: 
1. initialiser for stacked bar with data parameter — one data for whole stack

Demos: included star image to project, for stacked bar, pie, line, candle stick, bubble, bar and horizontal bar added Toggle Icon button and star to be drawn.

### CODE REVIEW

**Comment by AnatolyRosencrantz** [comment]
Okay, how do I fix this checks to be green? On my mac everything is built successfully for all platforms (iOS, OSX, tvOS)

**Comment by liuxuan30** [comment]
@AnatolyRosencrantz update the test cases? `In setup add record = true` from #https://github.com/danielgindi/Charts/pull/500

**Comment by AnatolyRosencrantz** [comment]
I've already generated those test images, put them to appropriate Tests/ReferenceImages_64/ folders (which is the only place I've found other test images). By some reason FBSnapshotTestCase was saving them under /Library/Developer/Xcode/DerivedData by default, btw.

**Comment by Anders123fr** [comment]
Really looking forward to this! :)

**Comment by AnatolyRosencrantz** [comment]
Guys, does somebody know where travis expects FBSnapshotTestCase's images to be? There are dozen of folders called "Tests" in project's directory

**Comment by petester42** [comment]
You don't have to move anything anywhere. When you record the tests they images will be placed in the right place. The setting for the path is an environment variable in the test scheme.

**Comment by farazhaider88** [comment]
any update on this ??

**Comment by AnatolyRosencrantz** [comment]
@farazhaider88 fighting with Travis to accept pr

**Comment by liuxuan30** [comment]
all pass! @danielgindi seems we can put this higher priority?

**Comment by Anders123fr** [comment]
I tried out the pull request in my project and I am having trouble aligning the icons in the center of the chart piece. I have tried some different values for the `iconOffset` but it doesn't help.

skaermbillede 2016-11-18 09 58 47

**Comment by AnatolyRosencrantz** [comment]
@Anders123fr, fixed that incorrect misplacement. So in case of Pie chart `iconOffset`'s x value stands for distance from center, so it should be 0 if you want icon's center to be placed where value's text is drawn by default. Could you check again and confirm if everything works as expected?

**Comment by Anders123fr** [comment]
Awesome, you just made my day! 
It works perfectly, and i am able to adjust how close the icon should be to the center of the pie chart using the `height` of the `iconOffset`. 
The screenshot shows a chart with `iconOffset` set to `CGSize(width: 0, height: -10)` 
skaermbillede 2016-11-21 10 01 43
Thank you!

**Comment by danielgindi** [comment]
This is getting better, and it seems like people are enjoying it :-)
I hope to get sometime to take a closer look soon, merge it, and port to Android

**Comment by AntonioFM92** [comment]
Why can't I see the file changed when I download this project from master? thanks

**Comment by AnatolyRosencrantz** [comment]
@AntonioFM92 cuz it was not merged to master yet

**Comment by MrMage** [comment]
This just saved me a ton of work (was going to implement this my self), thanks a ton!

One question, though: Is it possible in a pie chart view to render the icons _below_ the label text so that the two don't overlap? As was said before, at the moment, changing the offset draws the labels further outside rather than below.

**Comment by AnatolyRosencrantz** [comment]
@MrMage pushed a fix. Now iconsOffset for Pie and Radar charts represents (vertical offset; distance form center offset). 
- So if you want icon to be rendered below the value text label, you should use something like CGSize(width: 15, height: 0). 
- If you want icon to be rendered closer to center, you should use something like CGSize(width: 0, height: -15). 
- Sure, you can combine these two things like CGSize(15, -15) and icon will be 15 points below text label and 15 points closer to center. Looks strange, as for me, but legit.

**Comment by AnatolyRosencrantz** [comment]
@danielgindi still not a time? :)

**Comment by sashalondon** [comment]
Is this not Going to be in the main release?

**Comment by liuxuan30** [comment]
I believe they are busy :(

**Comment by danielgindi** [comment]
Yeah time is precious, but the good news is I'm working on this one :-)
You haven't by any chance coded this for Android yet have you?

**Comment by danielgindi** [comment]
There are a few coding style inconsistencies, but I'm not going to bug you about them right now; It's in the best interest of the users that we don't introduce any extra delays for this right now.
I'm suprised on how clean and little code this PR is, which means you understand how the library works.

**Comment by danielgindi** [comment]
There are a few bugs to polish though

**Comment by jainrohit2292** [comment]
I have updated my pods - **pod update Charts** but I can't find any property or method related to icon such as drawIconsEnabled

**Comment by askielboe** [comment]
This pull request hasn't been [released](https://github.com/danielgindi/Charts/releases) yet.

To use non-released features on the `master` branch you can install using:

    pod 'Charts', :git => 'git@github.com:danielgindi/Charts.git', :branch => 'master'

**Comment by sashalondon** [comment]
Any advice I have tried pod update and also askeilboe's advice but still cannot see this? I am using swift.
pod 'Charts', :git => 'git@github.com:danielgindi/Charts.git', :branch => 'master'

**Pull request merged**
