### PR TITLE
Bugfix for fix #1488, #1564

### LINKED ISSUE #1488: (v3.0 + Swift3.0) Time Line Chart Demo crash
## Time Line Chart Demo crash when xAxis direction Zoom in to largest status：
img_3297

## crash info:
```
fatal error: Index out of range
```

### PR DESCRIPTION
**Pull request by liuxuan30**
Attempt to fix #1488, #1564
@danielgindi I need you carefully review this and give details about existing implementation about centerAxisLabels feature. My changes may lack of information and cause more issues, though I have tesed it in time line chart, bar chart, combined chart, multiple bar chart, line chart.

1. I removed the dependency of getting initial `n` value, because `first` and `last` will be equal after zooming a lot
2. I change `centerAxisLabelsEnabled` condition, if entry count > 0, we could turn on centerAxisLabel. I need context why it's `> 1`.
3. I removed using local variable `centeringEnabled`, because `axis.entries` would be changed but `centeringEnabled` keeps reading old entryCount, which seems a dirty read issue
4. I use `offset: Double = interval / 2.0` instead of `offset = (axis.entries[1] - axis.entries[0]) / 2.0`, because `axis.entries[1] - axis.entries[0]` always equals to interval, and when there is only one entry, we still need a valid offset instead of 0

### CODE REVIEW

**Comment by liuxuan30** [comment]
@petester42 
seeing
```
*** Building scheme "Realm" in Realm.xcworkspace

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself
```
But no more logs.. Have you met this?

**Comment by petester42** [comment]
Ya realm takes too long to build on ci. Usually it's not a problem because the download limit is not reached. Just restart the build.

**Comment by danielgindi** [comment]
@PhilJay Looks good to me, right?

**Comment by danielgindi** [comment]
Okay I've done some adjustments and merged

**Pull request merged**
