### PR TITLE
Add dragging, scaling and decelerating variables to BarLineChartViewBase

### PR DESCRIPTION
**Pull request by kzyryanov**
In some cases it is good to have possibility to check if chart is being dragged, scaled or decelerated (like for UIScrollView)
#3251

### CODE REVIEW

**Comment by liuxuan30** [comment]
@jjatie what you think about making them public directly?
It's the first time I see someone want to know the state.

**Comment by kzyryanov** [comment]
@liuxuan30 @jjatie 
It's not a really often case, but if you want to make some complicated scroll (like scroll several chart views or chart view + some scroll view) you need to know the state (like UIScrollView has these readonly variables)

**Comment by liuxuan30** [comment]
@kzyryanov this PR looks most likely will be delay to 4.0 release, which contains our swift refactoring, leading by @jjatie. I found your code style maybe is not aligned with the new swift code style in the library. May I ask you to switch the branch to 4.0 and later when @jjatie came back, he could offer more insights and get this merged.

**Comment by jjatie** [comment]
As @liuxuan30 said, there is no reason to add new variables, just change the access control on the existing ones (and remove the `_` prefix). If we do accept this it will be in 4.x. I think the feature is something we should provide, but this is not how to do it.

Since you mentioned `UIScrollView`, I think it would make more sense for us to expose this information by providing a proper delegate similar to `UIScrollViewDelegate`. Now that I'm thinking about it, @liuxuan30 do you know why all of the charts aren't already subclasses of `UIScrollView`?

**Comment by liuxuan30** [comment]
@jjatie I think it should not be UIScrollView after all, as the zooming and panning are done by CoreGraphics directly, involving UIScrollView seems unnecessary.
Implementing a UIScrollChartView would be an interesting topic, but what I guess the UIScrollView's nature might cause more troubles than leveraging the scroll?

**Comment by sunnypurewal** [comment]
It should be noted that there is no private variable for isDecelerating so the only way to return that flag is to check if the display link is not null, just like in this PR.

**Comment by jjatie** [comment]
This functionality needs to be implemented for ScatterCharts, `CandleChart`, `BubbleChart` and `CombinedChart`. Exposing the information through a property means the only way to respond to it is through KVO, which is undesirable. This should be a delegate callback.

**Pull request closed without merging**
