### PR TITLE
Supports Xcode 8-beta 2

### PR DESCRIPTION
**Pull request by acegreen**

### CODE REVIEW

**Comment by liuxuan30** [comment]
is there any documentation for this change? beta 1: main -> beta 2: main() seems strange..

**Comment by smokyonion** [comment]
`RunLoopMode(rawValue: RunLoopMode.commonModes.rawValue)` or `RunLoopMode(rawValue: RunLoopMode.commonModes.rawValue)` could be simply replaced with `RunLoopMode.commonModes`

**Comment by liuxuan30** [comment]
@acegreen are you able to squash the commits? Seeing two reverts which are useless

**Comment by acegreen** [comment]
@liuxuan30 just built it against the latest beta

**Comment by liuxuan30** [comment]
@acegreen, yes I did, your commits be squashed into one or two, just make it easier to read what the PR did. 
Do you know how to do it?

**Comment by acegreen** [comment]
@liuxuan30 as far as I know there is no easy way to delete commits, except to rebase back to the earlier one and redo the work from there. Anyways if its sorted then its cool

**Comment by liuxuan30** [comment]
@acegreen you can try out SourceTree, it has convenient way to squash :) Just try it out!
I will update swift 3.0 soon, Thanks you for your involvement

**Pull request closed without merging**
