### PR TITLE
Add Privacy Manifest

### PR DESCRIPTION
**Pull request by wlxo0401**
**Issue Link 🔗**
https://github.com/danielgindi/Charts/issues/5131

**Goals ⚽**
add Privacy Manifest 

**Implementation Details 🚧**

**Testing Details 🔍**

I checked with CodeBase and thought 'DGCharts' had nothing to add to PrivacyInfo.

I think it will take a lot of people's opinions and tests to complete this.

Please check my PR and feel free to comment.

This resolves https://github.com/danielgindi/Charts/issues/5131

### CODE REVIEW

**Comment by wlxo0401** [comment]
Oh, my God. How do I fix this? "Some checks were not successful"

**Comment by pmairoldi** [comment]
If you want to test it out locally you can run `pod lib lint`. I think the path is wrong in the podspec. Seems like there is an extra `s`. Should be `Source` instead of `Sources` no?

**Comment by wlxo0401** [comment]
> If you want to test it out locally you can run `pod lib lint`. I think the path is wrong in the podspec. Seems like there is an extra `s`. Should be `Source` instead of `Sources` no?

**I changed it from**
s.resource_bundles = {"DGCharts" => ["Sources/Charts/PrivacyInfo.xcprivacy"]}

**to**

s.resource_bundles = {"DGCharts" => ["Source/Charts/PrivacyInfo.xcprivacy"]}

**Comment by wlxo0401** [comment]
@pmairoldi Thank you.

**Comment by wlxo0401** [comment]
I didn't set a target for PrivacyInfo, so I added a setting.

I don't know if this is necessary, but please review it.

**Review by ag-drivequant — APPROVED** [review]

**Comment by wlxo0401** [comment]
@pmairoldi 

Thank you for accepting the PR. 

However, I think it is also necessary to make sure that this is applied properly as Apple demanded. 

And I think other users will have to check it out a lot. 

If this is wrong, an immediate response may also be needed..

When is the new release that includes this?? 

Once again, thank you for your care in a busy time.

**Pull request merged**
