### PR TITLE
BubbleChart: The value on the y-axis. and not the size

### PR DESCRIPTION
**Pull request by thierryH91200**
if set.drawValuesEnabled = true
the size of bubble is draw

### CODE REVIEW

**Comment by liuxuan30** [comment]
@thierryH91200 just saw similar closed PRs for this and confused. Can you give some context for what does it try to solve?

**Comment by thierryH91200** [comment]
This is what I do

I created a clone of "Charts"
I go through GitHub Desktop (the lastest version)

I modify the source for a first problem
I create a "commit first problem" commit with a "push to remote" origin / master with Xcode
On github.com/therryH91200 I do a Pull Request n1
There everything goes well

I modify the same source again for a second problem
I create a commit "commit second problem" with a "push to remote" origin / master
On github.com/therryH91200 I do another Pull Request

There the Pull Request n2 is mixed with the first then I wanted to start 2 pull request separate

I might have to go through the terminal

**Comment by thierryH91200** [comment]
To illustrate the problem

**before**

capture d ecran 2017-04-18 a 08 24 33


**After**


capture d ecran 2017-04-18 a 14 07 14

**Comment by liuxuan30** [comment]
wow, can't believe no one founds it before :)

**Comment by thierryH91200** [comment]
You are completely right
Mea culpa
The size is independent of the position in OY

A bubble chart is a type of chart that displays three dimensions of data.


The representation should look like this



capture d ecran 2017-04-19 a 07 24 36

**Pull request closed without merging**
