### PR TITLE
Migrate to Swift 3 (now targeted at the Swift-3.0 branch)

### PR DESCRIPTION
**Pull request by pixelspark**
Like https://github.com/danielgindi/Charts/pull/1169, but targeted at the Swift-3.0 branch in the main repository.

### CODE REVIEW

**Comment by acegreen** [comment]
@pixelspark did you test your swift3 branch from your fork? I just tried it and there were a ton of open issues (iOS deployement)

**Comment by pixelspark** [comment]
@acegreen I just committed fixes for compilation errors on iOS and tvOS (https://github.com/danielgindi/Charts/pull/1171/commits/39cdf63c95c0883ea22bb837be121c9b0333136f). All should be fine now.

**Comment by acegreen** [comment]
@pixelspark just tried it out, works as expected

**Comment by liuxuan30** [comment]
@acegreen thanks, I will merge this

**Comment by acegreen** [comment]
@pixelspark @liuxuan30 there are some new issues with Xcode 8-beta 2

Charts not compiling, says no such module found.

**Comment by liuxuan30** [comment]
@acegreen able to help :)?

**Comment by acegreen** [comment]
@liuxuan30 done

**Pull request merged**
