### PR TITLE
Axis renderer protocol

### PR DESCRIPTION
**Pull request by jjatie**
Slight more code, but allows for better type safety and removes a lot of unnecessary type conversion. It's a "Swift-ier" way.

Note that this builds off the changes made in #2991

### CODE REVIEW

**Comment by jjatie** [comment]
@liuxuan30 @petester42 @danielgindi There are changes here that pave the way to much larger changes to the framework which allow better type safety and less reliance on optionals. This is PR is preceded by #2991. Once these two are approved, there will be more changes that can be quickly and easily made to greater improve the type safety and the use of optionals in across the entire framework.

**Comment by liuxuan30** [comment]
some of your PRs have conflicts. Any idea?
Also, thank you so much for improing, you are contributing a lot. But kind of stressful for so many changes in a short time. I guess we need a discussion first with @danielgindi and @petester42 ?

**Comment by jjatie** [comment]
The PRs have conflicts because others are being accepted and merged. I'll do a better job of keeping them up to date. Once #2980 is accepted and merged, #2991 and this one will be easier to review.

**Comment by liuxuan30** [comment]
feel PRs get a little messy. 

I just found out there is 4.0 branch for breaking changes. Can you add label for your PR to tag as 4.0? I can help review merge minor changes. But just get lost when finding some PRs that looks like for 4.0 branch.

What's the proposal for 4.0 branch? @jjatie do you switch all changes to 4.0 branch, and close existing one that's to master?

**Comment by danielgindi** [comment]
Thanks!

This looks like a refactoring-only PR, but it includes 44 commits. 
This should be squashed before merging... :-)

**Comment by petester42** [comment]
It can be squashed when clicking the merge button.

**Comment by liuxuan30** [comment]
yep, with "Squash and merge" option, it can be done all in once.

**Comment by jjatie** [comment]
The reason there's so many commits is because it's PRd into 4.0.0 which isn't up to date with master.

**Comment by danielgindi** [comment]
I've added @jjatie :-) Welcome aboard!
@liuxuan30 have told me that you were trying to get my attention, but the problem is that there are so many Github notifications from issues and PRs, that I can't read all of them and then I miss some important ones.

**Comment by jjatie** [comment]
Thanks @danielgindi

**Comment by jjatie** [comment]
Given this seems to be approved, I will assume #2991 is approved as well. I'll PR master into 4.0.0 and start merging in PRs that have been approved for 4.0.0

**Comment by liuxuan30** [comment]
@jjatie what's your proposal on reviewing 4.0 branch PRs? I asked in https://github.com/danielgindi/Charts/pull/3130, but seems not discussed.

**Comment by jjatie** [comment]
I'd say lets keep it the same as for the master.

Now that 4.0 and master will be getting different changes submitted to them, I will do my best to get the bug fixes from master into 4.0 and PR them for someone to review.

Also I think that all my changes should go in to 4.0 now. Unless I'm making a bug fix or something urgent, I think my changes are big enough that we should just move them all to 4.0 to keep the current release more stable.

**Comment by jjatie** [comment]
Continued in #3136

**Pull request closed without merging**
