### PR TITLE
fix the issue with axis dependencies

### PR DESCRIPTION
**Pull request by gGololicic**
Axis dependencies on combined charts were ignored. Fix to the issue https://github.com/danielgindi/Charts/issues/1830

### CODE REVIEW

**Comment by vojto** [comment]
Hi, 

this solves the problem for me – can we get this merged in?

Thanks!

**Comment by liuxuan30** [comment]
We need @danielgindi review and maybe check Android. Since every one is quite busy - we are sorry for that. But you can port it in your code first

**Comment by vojto** [comment]
@liuxuan30 No problem, I'm already using this happily. :) Thanks!

**Comment by kajensen** [comment]
+1

**Comment by nmdias** [comment]
This also fixed it for me. Thanks!

**Comment by liuxuan30** [comment]
Sorry that issue has been a long time and I don't recall a lot. I will revisit this and handle it.

**Comment by liuxuan30** [comment]
I need to use https://github.com/danielgindi/Charts/pull/2874 for CI test and add combined chart test. So have to close this. Thanks @gGololicic and other guys

**Pull request closed without merging**
