### PR TITLE
animated update for barchart

### PR DESCRIPTION
**Pull request by kevinjtchen**

### CODE REVIEW

**Comment by kevinjtchen** [comment]
no longer needed

**Comment by kditraglia** [comment]
Why is this no longer needed, is there another work-around that can get the effect you added here?

**Comment by cowgp** [comment]
Why is this not needed?  am I missing some other PR that has this functionality that did get merged?   I would really like to see this exact feature as build in this PR

**Comment by Jauzee** [comment]
@kevinjtchen can you please answer the questions above. I was looking for this functionality and came here.

**Pull request closed without merging**
