### PR TITLE
Added ability to fill highlighted circle.

### PR DESCRIPTION
**Pull request by matijag1**
Added ability to fill highlighted circle with highlighted color and also to make it larger when it is highlighted.

### CODE REVIEW

**Comment by liuxuan30** [comment]
Can't
```swift
    /// `true` if drawing circles for this DataSet is enabled, `false` ifnot
    var drawCircleHoleEnabled: Bool { get set }
```
solve the problem? It's in `fileprivate func drawCircles(context: CGContext)`

**Comment by matijag1** [comment]
Function 'drawCircles(context: CGContext)' is part of LineChartRenderer, and this is BubbleChartRenderer, so it can't help.

**Comment by liuxuan30** [comment]
Then we need some context about this PR.
Could you please provide some and maybe screenshots to demo? 

We need to evaluate if this is useful for most of the people or just your personal demand. If former, we may merge but if latter, you could subclass bubble chart and keep it in your class.

**Comment by jjatie** [comment]
Feel free to reopen @matijag1

**Pull request closed without merging**
