### PR TITLE
Create `chartViewDidEndAnimate` in ChartViewDelegate

### PR DESCRIPTION
**Pull request by Lcsmarcal**
### Goals :soccer:
Create a callback to get when ChartView stops animating

### Implementation Details :construction:
Create another function in `ChartViewDelegate` protocol and calls in `animatorStopped` callback from `Animator`

### CODE REVIEW

**Comment by liuxuan30** [comment]
@jjatie what you say? I'm fine

**Comment by jjatie** [comment]
I would think the delegate would include more information. This naming would also be more clear.
```
func chartView(_ chartView: ChartViewBase, animatorDidStop animator: Animator)
```

**Comment by liuxuan30** [comment]
@Lcsmarcal please have a look

**Comment by Lcsmarcal** [comment]
Sure! I will add the animator in function.

**Comment by Lcsmarcal** [comment]
Done :)

**Pull request merged**
