### PR TITLE
`ChartRenderer`'s must be initialized with a chart

### PR DESCRIPTION
**Pull request by jjatie**

### CODE REVIEW

**Comment by liuxuan30** [comment]
why is that?

**Comment by jjatie** [comment]
Does it make sense that a ChartRenderer has no chart to render?

My guess is this initializer parameter was made optional because the `weak` property declaration forced the property to be declared as optional.

**Comment by liuxuan30** [comment]
`@objc open weak var dataProvider: BarChartDataProvider?` is declared as weak, sounds like a historical reason or personal habit to use optional for params.

This change is in conjunction with https://github.com/danielgindi/Charts/pull/2981 to make animator non nil as well.

**Comment by jjatie** [comment]
Oops, I missed that one. Fixing now.

**Comment by jjatie** [comment]
Any PR that has a dependency on another as a comment indicating that. For the most part there are no dependencies.

**Comment by liuxuan30** [comment]
oops, conflicts. when you solve I will check again.

**Comment by jjatie** [comment]
@liuxuan30 Fixed, but pull #2980 first. While in some cases I might be able to consolidate some PRs, I think for the most part they should be separate.

**Comment by liuxuan30** [comment]
this can be next to merge?

**Comment by jjatie** [comment]
Yes, fixing now.

**Comment by jjatie** [comment]
Fixed

**Comment by liuxuan30** [comment]
need to use squash to merge

**Pull request merged**
