### PR TITLE
weak -> unowned

### PR DESCRIPTION
**Pull request by jjatie**
`ViewPortJob`s are owned by the Charts that make them. They are guaranteed to only exist while the chart exists. The `Transformer` and `ViewPortHandler` are supplied by the chart, so they will also only exist while the chart exists. Therefor none of them need to be `weak`, but can be `unowned` instead. It's a minor change in the code base (removing some guard statements), but it makes it much easier to discern how the framework is architected.

### CODE REVIEW

**Comment by liuxuan30** [comment]
CI is not latest? Please pull 4.0

**Comment by jjatie** [comment]
@liuxuan30 done

**Comment by liuxuan30** [comment]
let's wait result

**Comment by jjatie** [comment]
@liuxuan30 Any idea why Travis CI isn't running anything?

**Comment by liuxuan30** [comment]
don't know.. I will cancel and requeue

**Comment by liuxuan30** [comment]
I just found many CI is still in created state. I will try if I could contact Travis

**Comment by liuxuan30** [comment]
they are saying 
>We are currently investigating an increased back log for container-based infrastructure. 

Guess that's the reason?

**Comment by liuxuan30** [comment]
I have restarted the top 3 PRs' CI. Let's see if it can get started.

**Comment by jjatie** [comment]
Travis says it's fully operational again. I just tried restarting this one again.

**Comment by liuxuan30** [comment]
@jjatie we can move forward now.

**Pull request merged**
