### PR TITLE
Fixed a crash while zooming in the chart

### PR DESCRIPTION
**Pull request by S3Paramasivan**
Change done -
Checked for isNan on both on 1) AxisRendererBase.swift and YAxisRendererRadarChart.swift

### CODE REVIEW

**Comment by S3Paramasivan** [comment]
Does the below line mean that you will not commit the change into your repository?

>>>>>>Merging #4044 into master will not change coverage.

What should i do so that my next pull will have these changes so that the app will not crash while zooming in the chart?

**Comment by liuxuan30** [comment]
why range is NAN after your zooming? Can you post the log/data, etc?

For all NAN issues, we need to verify why it's NAN in the first place

**Comment by S3Paramasivan** [comment]
It did not happen during development, in production, it is happening for half of the users.

**Comment by liuxuan30** [comment]
if it's happening for half of your users, it should be easy to find out why. I'm asking for the data value that cause it. Usually you should validate the data first.

I'm holding all NaN PRs to understand why there is NaN in the first place, but so far I didn't get any feedback. The problem is we could definitely silence the crash, however it just hides the chance to find out the issue. Silencing NaN crash and proceed, usually it will make renderer wonder what to draw, either give you a blank space, or a default thing? IMO it's not renderer's job to decide what to do, but the users.

**Comment by S3Paramasivan** [comment]
> if it's happening for half of your users, it should be easy to find out why. I'm asking for the data value that causes it. Is it our fault during calculating, or yours passing an invalid value?
> 
> I'm holding all NaN PRs to understand why there is NaN in the first place, but so far I didn't get any useful feedback. The problem is we could definitely silence the crash, however it just hides the chance to find out the issue. If we silence NaN crashes and proceed, usually it will make renderer wonder what to draw, either give you a blank space, or a default axis? IMO it's not renderer's job to decide what to do, but the users.

You are correct, i will try to get some data causing the issue soon. Thank you.

**Pull request closed without merging**
