### PR TITLE
Fixed X-Axis Labels Not Showing (#3154)

### LINKED ISSUE #3154: X-Axis Labels not showing
I have the below function that I use to set up a simple bar chart. The resulting chat appears but with no x-axis labels on the chart at all. I am not sure if I missed something in my set up of the chart that would leave the x-axis labels off.

```
 func setChart(chartview: BarChartView, xarray: [String], yarray: [Double], count: Int){
        
        
        var dataEntries: [BarChartDataEntry] = []
        
        
        for i in 0..<xarray.count {
            
            let dataEntry = BarChartDataEntry(x: Double(i), y: Double(yarray[i]))
            
            dataEntries.append(dataEntry)
        }
        
        
        let chartDataSet = BarChartDataSet(values: dataEntries, label: "")
        
        chartDataSet.drawValuesEnabled = true
        
        let chartData = BarChartData(dataSet: chartDataSet)
        
        let format = NumberFormatter()
        
        format.numberStyle = .none
        
        let formatter = DefaultValueFormatter(formatter: format)
        
        chartData.setValueFormatter(formatter)
        
        chartview.xAxis.valueFormatter = IndexAxisValueFormatter(values:xarray)
        
        chartview.xAxis.granularityEnabled = true
        
        chartview.xAxis.labelPosition = .bottom
        
        chartview.chartDescription?.enabled = false
        
        chartview.rightAxis.axisMinimum = 0.0
        
        chartview.leftAxis.axisMinimum = 0.0
        
        
        chartview.legend.enabled = false
        
        chartview.xAxis.drawGridLinesEnabled = false
        
        chartview.rightAxis.drawLabelsEnabled = false
        
        chartview.rightAxis.drawGridLinesEnabled = true
        
        chartview.xAxis.setLabelCount(count, force: false)
        
        
        chartview.data = chartData
        
        
    }
```

### PR DESCRIPTION
**Pull request by leedsalex**
Fixes #3154

Corrected a mistake in the guard statement.

### CODE REVIEW

**Comment by sundeepios** [comment]
Please let me know when this fix will be released..so that i can use this code.

**Comment by jjatie** [comment]
3.1 is scheduled for the end of the month.

**Comment by mikeCalvir** [comment]
I still have this problem whichever version I install, I'm hoping v3.1 will fix it - is it likely to be be published soon? (Apologies if this information is publicly visible somewhere here, I couldn't find it on the Releases page).

**Comment by jjatie** [comment]
It will be released very soon!

**Comment by liuxuan30** [comment]
@mikeCalvir have you tried latest master branch? or this PR fixed your issue?

**Comment by mikeCalvir** [comment]
Thanks for the update.
I fixed it by changing to 3.0.4, but also the most critical change it seems was to set wrapEnabled=false on the X Axis, if it it set to true then they never show on any version.

I'll try master again now.

**Comment by mikeCalvir** [comment]
They are showing correctly in master

**Pull request merged**
