### PR TITLE
Swift 3.0 - Xcode 8 Beta 4

### PR DESCRIPTION
**Pull request by acegreen**
Conforms To Xcode 8 Beta 4

### CODE REVIEW

**Comment by liuxuan30** [comment]
@acegreen first, please do not merge into master. second, please pull and rebase on current swift 3.0 branch, I see this PR contains old commits (like mine), this is not normal.. Ideally, only ' 	Conforms To Xcode 8 Beta 4' should be presented.

**Comment by acegreen** [comment]
@liuxuan30 or you can close this PR and redo it yourself. This is my second attempt and if you don't like it, whatever.

**Comment by liuxuan30** [comment]
@acegreen I'm sorry but I don't mean to hurt you your feeling but.. we have to follow some rules and once you master it it's very easy

**Comment by acegreen** [comment]
You don't hurt my feeling :) but like on the last branch, there was no reason to do your own PR. Anyways this is what it is, use it in your own PR but thats it on my end

**Pull request closed without merging**
