### PR TITLE
Minor fixes for API changes with Swift 4.2

### PR DESCRIPTION
**Pull request by jjatie**
### Issue Link :link:
Compiler warnings and errors regarding new API changes

### CODE REVIEW

**Comment by petester42** [comment]
Already released but thanks anyways!

**Comment by dclelland** [comment]
You should merge this anyhow, these errors are bugging me also

**Comment by petester42** [comment]
I did these changes too

**Comment by dclelland** [comment]
Oh, I missed that, sorry and thanks!

**Pull request closed without merging**
