### PR TITLE
'backgroundColor' is inaccessible due to 'internal' protection level …

### PR DESCRIPTION
**Pull request by thierryH91200**
…on mac OS X #2135

### CODE REVIEW

**Comment by petester42** [comment]
Thanks!

**Comment by liuxuan30** [comment]
sorry to bring this up, but what's `wantsLayer` for? Don't see it's used

**Comment by thierryH91200** [comment]
with wantsLayer


capture d ecran 2017-02-14 a 03 07 08

without wantsLayer


capture d ecran 2017-02-14 a 03 07 56

haye you another solution ??

**Comment by liuxuan30** [comment]
oh sorry, I didn't realize it's about NSView. Just search in the project and not seeing it's used anywhere else.

**Pull request merged**
