### PR TITLE
Fill rewrite

### PR DESCRIPTION
**Pull request by jjatie**
Fill is now a protocol

Different fill logic is broken up into separate classes. This has a few benefits:
1. It makes the `Fill` types more readable (logic is grouped together)
2. No optionals
3. Most importantly it allows consumers to create new Fill types without looking into the framework.

### CODE REVIEW

**Comment by jjatie** [comment]
How are branches kept in sync with `master`?

**Comment by jjatie** [comment]
@liuxuan30

**Comment by liuxuan30** [comment]
@jjatie I saw you closed several PRs. is this the only left to merge?
have to fix the demo btw, CI failed 
>❌  /Users/travis/build/danielgindi/Charts/ChartsDemo-iOS/Objective-C/Demos/LineChart1ViewController.m:177:22: use of undeclared identifier 'ChartFill'
        set1.fill = [ChartFill fillWithLinearGradient:gradient angle:90.f];

**Comment by liuxuan30** [comment]
Merged, marking swift refactor project is done!

**Pull request merged**
