### PR TITLE
Fix RangeReplaceableCollection protocol implementation for 3.6 version

### PR DESCRIPTION
**Pull request by flaviosuardi**
### Issue Link :link:
https://github.com/danielgindi/Charts/issues/4873

### Goals :soccer:
I fix problem related to RangeReplaceableCollection protocol implemented on ChartDataSet adding replaceSubrange method for 3.6 version.

### Testing Details :mag:
I just rebuild project and no build errors occur on Xcode 14.0.

### CODE REVIEW

**Comment by JGVB** [comment]
Please merge this so charts is useable on xcode 14.

**Comment by lucasiturbide** [comment]
the base branch is outdated in `tiknil` repository, master branch in `danielgindi` is actually already fixed.

**Comment by KaranVakharia789** [comment]
I fixed it.
please check below link:
https://stackoverflow.com/questions/74010925/charts-not-compile-on-xcode-14

**Comment by liuxuan30** [comment]
as @lucasiturbide said, we cannot merge this onto master

**Pull request closed without merging**
