### PR TITLE
Rounded bars

### PR DESCRIPTION
**Pull request by idcuesta**
## JIRA
- [ORCHID-2602](https://cipherhealth.atlassian.net/browse/ORCHID-2602)

## Description
This PR add next changes in order to be able to reproduce design for bar charts as described in this image:

bar-charts

- [x] Added rounded corners to bars in bar chart through config option `drawRoundedBarEnabled`
- [x] Added rounded lines to legend form through config option `formLineRoundedCap`

### CODE REVIEW

**Comment by liuxuan30** [comment]
which rounded bar PR is this PR derived from? Or the code is writen by yourself?
We have #4339 #1917

**Comment by liuxuan30** [comment]
it looks like similar from #1917 , which I think not as good as #3754.

**Comment by liuxuan30** [comment]
I will have to close this as we already had similar PRs. becides, it changes line renderer.

**Comment by idcuesta** [comment]
Ups, apologies, this was supposed to be added to our own fork, not here

**Comment by liuxuan30** [comment]
@idcuesta I'd suggest you take a look at $3754, which seems a better solution.

**Comment by idcuesta** [comment]
Thanks! I have seen that PR, waiting for it to get merged (this solution is just a simplistic patch for what we need at the moment) 👍

**Pull request closed without merging**
