### PR TITLE
Remove Realm binaries from project and fix carthage building

### PR DESCRIPTION
**Pull request by petester42**
This change address two issues having to do with Carthage (#1326 and #1119). 

This first change is removing the prebuilt binaries inside of the ChartsRealm project and replacing them with ones that come from Carthage when running "carthage bootstrap" or "carthage update". There has been a lot talk in #1119 about the possible solutions and to me this seems to be the best for now. This means that contributors wanting to update the ChartsRealm project will have to have Carthage install and run "carthage bootstrap" to get the Realm dependencies. A note in the CONTRIBUTING.md should be added for newcomers. 

The second change sort of goes hand in hand with the first. It changes how ChartsRealm requires Charts.framework in order to work with Carthage. For whatever reason when building using Carthage most of the time it will pick the macOS version of Charts.framework (but not all of the time, its weird). So instead of having the ChartsRealm project depend on Charts.framework from the Charts project it now depends on Charts.framework built by Carthage.

I believe this addresses most of the Carthage issues. It seems to work consistently now.

### CODE REVIEW

**Comment by petester42** [comment]
This should be good for review now @danielgindi or @liuxuan30. Let me know what you think.

**Comment by liuxuan30** [comment]
seems still have dependency for Charts.framework to require Realm?

**Comment by petester42** [comment]
I'm not sure I understand what you mean. But I think I'm gonna close this. I found a better way.

**Comment by liuxuan30** [comment]
never mind :)

**Comment by petester42** [comment]
close in favour of #1422

**Pull request closed without merging**
