### PR TITLE
Removed optionality from valueFormatter where appropriate

### PR DESCRIPTION
**Pull request by jjatie**
In ChartBaseDataSet, `valueFormatter` never returned nil, and escaped early if trying to set it to nil. It appears this was made optional solely to provide lazy initialization. We now use a lazy var instead. This also removes the need for `needsFormatter`

In AxisBase, the backing var `_axisValueFormatter` would never be treated as nil, and appears to be made optional solely to provide lazy initialization. We now use a lazy var instead. In `valueFormatter` we can remove the `nil` check, but leave it optional to keep the same functionality.

### CODE REVIEW

**Comment by jjatie** [comment]
@liuxuan30 This has the xcodeproj issue again. I think it comes from being originally on master, and me changing it to 4.0.0

**Comment by liuxuan30** [comment]
I think it's your tab/space mess up issue as I said in another thread. You can look it up see what's wrong. By default Xcode project is using tab. However in your commit it changes to space.

**Comment by liuxuan30** [comment]
conflict and issue with project.pbxproj

**Comment by jjatie** [comment]
Fixed

**Comment by jjatie** [comment]
@liuxuan30 fixed

**Comment by liuxuan30** [comment]
weird, the xproj issue happens again...

**Comment by jjatie** [comment]
ugh. I'll fix it.... Let's see what happens after #3039 gets merged first though. Can you review the rest of it and approve/comment. That way I can merge it when I fix the xproj issue if you're not around.

**Comment by liuxuan30** [comment]
This change is ok except for the project file. Do you think you can fix it? 
two options if cannot fix:
1. mix reset, only commit other changes
2. merge, and we revert project file change

**Comment by jjatie** [comment]
I will fix it if #3039 doesn't fix it.

**Comment by liuxuan30** [comment]
we can merge #3039 now

**Comment by liuxuan30** [comment]
travis is really slow now.. almost 48H and tvOS is still pending.. the other two passed.

**Comment by jjatie** [comment]
Yea. When I check (about 12 hours ago) the backlog was at 1800

**Pull request merged**
