### PR TITLE
Add support for extensions

### PR DESCRIPTION
**Pull request by raptorxcz**
This pull request adds option to use in library extensions.

### CODE REVIEW

**Comment by liuxuan30** [comment]
Thanks, can you give an example how this works? what extension?

**Comment by raptorxcz** [comment]
I am creating today extension. In extended mode I want to show simple graph. This library is great except without this pull request I can not use it in extension.

**Comment by liuxuan30** [comment]
mind to share a screenshot? You mean using this library to show a chart in widgets?

**Comment by raptorxcz** [comment]
Yes exactly. Image of graph

**Comment by liuxuan30** [comment]
Wow, I don't know Apple opened this to us. I remember it has been forbidden to show such things.

**Pull request merged**
