### PR TITLE
For #2840. add dataIndex parameter in `highlightValue()` calls

### PR DESCRIPTION
**Pull request by liuxuan30**
for #2840. add dataIndex parameter in `highlightValue()` calls. Default is -1

### CODE REVIEW

**Comment by jjatie** [comment]
@liuxuan30 I agree with you in #2840, but if you think we should add this, let's merge it.

**Comment by liuxuan30** [comment]
what you think of this PR itself?

**Comment by jjatie** [comment]
I think we can reduce them all to one function:
```
@objc open func highlightValue(x: Double, y: Double = .nan, dataSetIndex: Int, dataIndex: Int = -1, callDelegate: Bool = true)
```

**Comment by liuxuan30** [comment]
I will take a look later tomorrow

**Comment by liuxuan30** [comment]
actually there is only one method left to use the full method footprint, and chaining up maybe better now. I would stick to current one.

**Pull request merged**
