### PR TITLE
Alternative for SPM dynamic linking

### PR DESCRIPTION
**Pull request by alexruperez**
We need [dynamic linking](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescription.md#methods-2) for this dependence.

---
This change is [Reviewable](https://reviewable.io/reviews/danielgindi/charts/4478)

### CODE REVIEW

**Comment by jjatie** [comment]
@alexruperez Could you elaborate on why you need dynamic linking for Charts? I am curious what the use case is.

**Comment by alexruperez** [comment]
@jjatie we have Charts integrated in a dynamic framework through Swift Package Manager, when trying to integrate this framework into other dynamic frameworks and in our app, being static, it gives duplicated symbols error.

**Comment by jjatie** [comment]
Makes sense. You'll need to ensure CI is passing.

**Comment by alexruperez** [comment]
The CI is failing, but not from this MR code. 😞 

```bash
==> java has been moved to Homebrew.
To uninstall the cask run:
brew cask uninstall --force java
==> Installing java...
Warning: openjdk 13.0.2+8_2 is already installed and up-to-date
To reinstall 13.0.2+8_2, run `brew reinstall openjdk`
The command "brew update" failed and exited with 1 during .
```

**Review by danicoello — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/danielgindi/charts/4478)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by alexruperez** [comment]
@jjatie @danielgindi @danicoello @liuxuan30 ready for merge! 😃

**Review by jjatie — APPROVED** [review]

**Comment by alexruperez** [comment]
When will be available a new release with this changes? Thanks.
CC: @jjatie @danielgindi @danicoello

**Comment by liuxuan30** [comment]
emm, not sure if we want to release a minor version for this. We are planning a 4.0 release soon, at least like a pre release, as it's a very big change and upgrade

**Pull request merged**
