### PR TITLE
- Proposed change on algorithm change the bubble normalize on the size.

### PR DESCRIPTION
**Pull request by chuynadamas**
Added enums to choose betweetn two different normalize types on bubble chart - #1081 

This changes enable the user to switch between two ways to calculare the size of the bubbles on the bubble chart, he can still using the sqrt based one, or just use the normal one wich increase the preccision of the size of every chart

### CODE REVIEW

**Comment by lidgardo** [comment]
Do you have any idea why CI Travis is thoewing me, this error:

```
$ cd Charts && carthage bootstrap
*** Cloning ios-snapshot-test-case
*** Skipped downloading ios-snapshot-test-case.framework binary due to the error:
	"Maximum number of login attempts exceeded. Please try again later."
*** Checking out ios-snapshot-test-case at "2.1.1"
*** xcodebuild output can be found in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/carthage-xcodebuild.UWg3ft.log
*** Building scheme "FBSnapshotTestCase tvOS" in FBSnapshotTestCase.xcworkspace
** BUILD FAILED **
```
I wasn't able to create the pull request 😞

**Comment by ikesyo** [comment]
@lidgardo @danielgindi Could you please follow https://github.com/facebook/ios-snapshot-test-case/pull/169?

**Comment by liuxuan30** [comment]
off topic question for @ikesyo, I just tried on my machine, I did see your PR code change after carthage update, however, I am still facing 
```
xuanliu:Charts xuanliu$ carthage bootstrap
*** Checking out ios-snapshot-test-case at "2.1.1"
*** xcodebuild output can be found in /var/folders/8v/6dg7d6mx2850sv1gp8ts9thm0000gn/T/carthage-xcodebuild.k5lDlQ.log
*** Building scheme "FBSnapshotTestCase tvOS" in FBSnapshotTestCase.xcworkspace
** BUILD FAILED **


The following build commands failed:
	Ld /Users/xuanliu/Library/Developer/Xcode/DerivedData/FBSnapshotTestCase-fvsqabvvnjtynnawvxrndncxsumy/Build/Products/Release-appletvos/FBSnapshotTestCase.framework/FBSnapshotTestCase normal arm64
(1 failure)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/xuanliu/Development/GitHub/ios-charts/Charts/Carthage/Checkouts/ios-snapshot-test-case/FBSnapshotTestCase.xcworkspace -scheme FBSnapshotTestCase tvOS -configuration Release -sdk appletvos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Ld /Users/xuanliu/Library/Developer/Xcode/DerivedData/FBSnapshotTestCase-fvsqabvvnjtynnawvxrndncxsumy/Build/Products/Release-appletvos/FBSnapshotTestCase.framework/FBSnapshotTestCase normal arm64
(1 failure)
```
what should we do? my understanding is this should be done by travis?

**Comment by ikesyo** [comment]
@liuxuan30 https://github.com/facebook/ios-snapshot-test-case/pull/169 is merged but not included in a new tagged release yet. Charts specifies the dependency as follows: `github "facebook/ios-snapshot-test-case" ~> 2.1`, so Carthage will fetch its latest tagged version.

> *** Checking out ios-snapshot-test-case at "2.1.1"

You should specify `master` branch for now in `Charts/Charts/Cartfile.private`: `github "facebook/ios-snapshot-test-case" "master"`.

**Comment by ikesyo** [comment]
And also Carthage 0.17.1 is required to build successfully for this, so you should run `brew update` and `brew upgrade carthage` on Travis (today's pre-installed version is 0.16.2).

**Comment by liuxuan30** [comment]
@ikesyo thanks so much! I have filed a PR: #1202, Let's move the feture dicussion there if needed.

**Comment by liuxuan30** [comment]
@lidgardo would you please rebase with master in order to run the tests?

**Comment by chuynadamas** [comment]
@liuxuan30 @ikesyo  Hope this time works 💯  and thanks for the help.

**Comment by liuxuan30** [comment]
Yep it passed.
if you can squash is way more better :) a new commit 'merge with master' is not needed, though it's ok since only 2 commits here

**Comment by chuynadamas** [comment]
@liuxuan30 I guess, I missunderstand what you mean 😁, but I hope that the PR be functional for the Charts 👍 

Thanks in advance.

**Comment by liuxuan30** [comment]
@chuynadamas You mean 'squash'? Using SourceTree can squash the commits into one. It's not a must, but useful when the commits logs are verbose

**Comment by liuxuan30** [comment]
BTW, this kind of refactoring may take longer time, as @danielgindi will be back later this weekend and review this.

**Comment by liuxuan30** [comment]
what happened..

**Comment by chuynadamas** [comment]
I just did a little clean over my repo and I erased the branch by mistake :p I'll reopen this later.

**Pull request closed without merging**
