### PR TITLE
Renderer protocol

### PR DESCRIPTION
**Pull request by jjatie**
`Renderer` and `DataRenderer` are now protocols instead of classes.

### CODE REVIEW

**Comment by jjatie** [comment]
There are changes here that pave the way to much larger changes to the framework which allow better type safety and less reliance on optionals. This is immediately followed by #2990. Once these two are approved, there will be more changes that can be quickly and easily made.

**Comment by jjatie** [comment]
This includes #2980

**Comment by jjatie** [comment]
@liuxuan30 After #2982 I think this one should be done next (and #2990)

**Comment by liuxuan30** [comment]
oops just read your comment.
I would suggest you create an issue to track your PRs, like which are for 4.0 branch and which can be merged into master directly. I feel dizzy switching around the PRs not sure which to start with. Some "minor" changes have hundreds of diffs, which are not minor to review.

I would first start with diffs that are just two digits and later with the big ones.

**Comment by jjatie** [comment]
I'll just change the destination branch on the PR

**Comment by jjatie** [comment]
In the future I will create Issues and name the PRs after them.

**Comment by jjatie** [comment]
Continued in #3136

**Pull request closed without merging**
