### PR TITLE
Removed @objc from internal properties

### PR DESCRIPTION
**Pull request by jjatie**
Since the framework is entirely Swift, internal properties do not need to be marked as @objc

### CODE REVIEW

**Comment by jjatie** [comment]
@liuxuan30 This is a quick and easy one.

**Comment by liuxuan30** [comment]
if it contains more than 3 files it's not a quick one lol

**Comment by liuxuan30** [comment]
I remember we just added those tags since swift 4.
>**Internal** access enables entities to be used within any source file from their defining module, but not in any source file outside of that module. You typically use internal access when defining an app’s or a framework’s internal structure.

Does this mean no one need access to these internals outside Charts framework anymore? If true, we can remove then.

**Comment by jjatie** [comment]
the internal access method means that the properties/methods can only be used within the Charts framework. Any consumer of the framework cannot see them.

Since any consumer of the framework cannot see them, and the framework is written in Swift internally, all internal and private functions and properties do not need to be marked as `@objc` because they will never be used by objective-c

**Comment by liuxuan30** [comment]
yes, but the trick is adding @objc will let Objc see it and break the rules

**Comment by liuxuan30** [comment]
for math refineing I have to delay one day. get back to work

**Pull request merged**
