### PR TITLE
added highlightColor parameter for pie charts

### PR DESCRIPTION
**Pull request by pascalherrmann**
Added attribute `highlightColor` to specify a color for highlighted pie chart sectors.

### CODE REVIEW

**Comment by liuxuan30** [comment]
wow, I don't realize pie chart does not support highlightColor.
@danielgindi for feature or enhancements like this, shall we go ahead or still need sync with Android?

**Comment by petester42** [comment]
Looks good to me. If this needs to be ported to android it's fairly simple. I think we should take ownership of the project's direction since @danielgindi isn't here a lot. The issues and pull requests are piling up and we can't always wait for @danielgindi to review. We should also add more contributors to help with the load.

**Comment by liuxuan30** [comment]
ok sure. but how about the "more swift-y" changes? those are kind of heavy; and seems we need a swift expert to make some feedback. are you able to do that? I'm not having enough time to keep up with the swift trend. I'm afraid I am more learner than reviewer for those changes.

**Comment by petester42** [comment]
Ya sure. Things being more “swifty” just really means the code should be easy to read. Read more like a sentence then instructions.

**Pull request merged**
