### PR TITLE
Restored old performance in ChartDataSet

### PR DESCRIPTION
**Pull request by jjatie**
for https://github.com/danielgindi/Charts/issues/3166
Temporary fix for calcMinMax frequency.
Better implementation coming for Charts 4

### CODE REVIEW

**Comment by liuxuan30** [comment]
hmm.. what PR is before this invert? I don't remember you particularly have a performance enhance PR？

**Comment by jjatie** [comment]
I don't know which one was the problem. I think it was when I moved to the `didSet`. I think it's important we have a fix for now, I have a good idea on how to improve it in 4.0.

**Comment by liuxuan30** [comment]
Weird I didn't catch this performance drop.

**Comment by liuxuan30** [comment]
wait a minute. I checked it's #3000 
```swift
    @objc open var values: [ChartDataEntry]
    {
        get
        {
            return _values
        }
        set
        {
            _values = newValue
            notifyDataSetChanged()
        }
    }
```
I didn't see `didSet` or `set` has any difference

**Comment by liuxuan30** [comment]
eh, I kind of start to recall. `didSet` will be called for Array type every time an element is added in or removed, is that correct? That's the drop

**Comment by liuxuan30** [comment]
@jjatie do you think it's the right behavior for `didSet` on collection types? I will keep an eye on if swift evolution would address this. Kind of confusing.

**Comment by jjatie** [comment]
Yes, that’s the reason why. didSet is called whenever the underlying data mutates (excluding direct memory access). A computed variable doesn’t have underlying data, so it doesn’t make sense for it to be called on append/remove. 

There’s a couple of major architectural changes I’m going to make over the next couple weeks. After that I’ll work in making performance better for 4.0

**Comment by liuxuan30** [comment]
@jjatie take some rest.

**Pull request merged**
