### PR TITLE
Update Charts for Swift 5 compiler

### PR DESCRIPTION
**Pull request by alanzeino**
### Goals :soccer:
Swift 5 compiler warnings

### CODE REVIEW

**Comment by liuxuan30** [comment]
there is already #3874

**Comment by alanzeino** [comment]
> there is already #3874

#3874 is not backwards compatible with Swift 4.2. I think my change is the correct one and should be merged.

**Comment by liuxuan30** [comment]
@alanzeino if so, I think @jjatie could work with you to address your issues in that PR. I'm ok to either reopen yours and close #3874.

**Comment by alanzeino** [comment]
> @alanzeino thanks for pointing out the difference, I think @jjatie could work with you to address your issues in that PR. I'm ok to either reopen yours and close #3874.

I'll wait for @jjatie to comment, but this PR is thorough and complete and can be merged now.

**Comment by liuxuan30** [comment]
@jjatie what you think?
@alanzeino he may be busy with this work. so let's wait.

**Comment by jjatie** [comment]
I don't see any reason to have this merged now. Swift 5 is not out yet, and we have yet to support previous versions of Swift through availability checks. Until module stability is locked in for Apple platforms, there isn't a strong reason to either.

**Comment by alanzeino** [comment]
>I don't see any reason to have this merged now. Swift 5 is not out yet, and we have yet to support previous versions of Swift through availability checks. Until module stability is locked in for Apple platforms, there isn't a strong reason to either.

@jjatie Swift 5 and Xcode 10.2 are about a week or two away but if you want to wait that’s fine.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
