### PR TITLE
Pie chart with value line : add an image view to be visible beside Label

### PR DESCRIPTION
**Pull request by maryamfekri**
According to issue [PieChart, adding an imageView beside values #2318](https://github.com/danielgindi/Charts/issues/2318#issuecomment-301737890) :

to achieve the pie chart with value lines like below : 
screen shot 2017-04-05 at 3 15 38 pm

**Added feature** : adding image in pie chart with value lines: 
 which the image will be shown beside the chart value. you can set the data chart with UIImageViews, and they will be shown in just pie chart with value beside the label value.

### CODE REVIEW

**Comment by maryamfekri** [comment]
@liuxuan30 here is the updated pull request,

**Comment by liuxuan30** [comment]
sure, but need @danielgindi review

**Comment by maryamfekri** [comment]
@danielgindi please review my commit and merge if possible, cause we want to use it in our project

**Comment by liuxuan30** [comment]
@danielgindi has been busy for some time and I don't know when he will come back and review new features. You can keep it in your branch or make a subclass and use it in your project. Sorry about that.

**Comment by maryamfekri** [comment]
Thanks @liuxuan30 , I have done so, and I will still wait for the merge.

**Comment by maryamfekri** [comment]
@danielgindi , @liuxuan30  take a look at this one please

**Comment by jjatie** [comment]
@liuxuan30 can we consider this for 3.1 or 4.0.0?

**Comment by liuxuan30** [comment]
I guess new features or major enhancement could be 4.0. If we want to reach 3.1 date, seem too much on plate?

**Comment by jjatie** [comment]
@maryamfekri please rebase onto 4.0.0

**Comment by maryamfekri** [comment]
@jjatie  @liuxuan30 I updated my fork and I created another pull request here   #3206 
I think its ready to merge now 👍

**Comment by liuxuan30** [comment]
so this can be closed

**Pull request closed without merging**
