### PR TITLE
Allow PieChartView to hide labels for tiny slices - Swift 3

### PR DESCRIPTION
**Pull request by hugobisson**
This refer to pull request _#944 - Allow PieChartView to hide labels for tiny slices_ but in swift 3

### CODE REVIEW

**Comment by amycheong19** [comment]
May I know what's the status of this merge conflict?

**Comment by liuxuan30** [comment]
@jjatie seems we can take it a higher priority? I just saw two new issues about this

**Comment by jjatie** [comment]
@liuxuan30 agreed. I think the default behaviour should be to hide smaller labels too. If @hugobisson  of this PR doesn't update it in the next few days, I will add it. Should this be targeted to 3.x or 4.0.0? I'm thinking 4.0.0 could be ready by the end of April (depending on how review goes)

**Comment by liuxuan30** [comment]
I'm ok either 3.x or 4.0. just make it easier to merge and fix conflicts.

**Comment by jjatie** [comment]
@hugobisson Can you fix this?

**Pull request closed without merging**
