### PR TITLE
Add missing properties to copy(with:) methods

### PR DESCRIPTION
**Pull request by dstranz**
## Issue Link :link:
#3578 

### Goals :soccer:
* Add missing properties to copy(with:) methods

### Implementation Details :construction:
Add any missing property to copy(with:) methods

### Testing Details :mag:
I didn't add any tests cases, but if you think it will be valuable let me know.

#hacktoberfest #coinpaprika

### CODE REVIEW

**Comment by liuxuan30** [comment]
thanks for this PR. I wonder if this is a complete list for now?

btw, I wonder if there is better ideas/solutions, because people would add new properties without remembering to add in copy(). Either could we tell whether we must add in copy(), or any smart way to auto add, or just by reviewers have to keep it in mind

@jjatie any thoughts

**Comment by jjatie** [comment]
Really, the only way to keep on top of this is to do it by hand. One solution would be to implement the data model as Swift structs, but only expose them through classes. We get copy semantics and only have to add one property to the `copy` override i.e:

```
internal struct DataEntry: Equatable {
    let x: Int
    let y: Int
}

@objc
public class ChartDataEntry: NSObject {

    internal private(set) var entry: DataEntry

    var x: Int {
        get { return entry.x }
        set(x) { entry.x = x }
    }
    
    var y: Int {
        get { return entry.y }
        set(y) { entry.y = y }
    }

    func copy(with zone: NSZone? = nil) -> Any {
        let copy = type(of: self).init()
        copy.entry = entry
    }
}
```

It might be possible too, to create a protocol for this i.e.
```
protocol DataEntryProtocol {
    var x: { get set }
    var y: { get set }
}

extension DataEntry: DataEntryProtocol { }
extension ChartDataEntry: DataEntryProtocol { }
```

Then we could update our API to accept the protocol instead of the concrete type. This would allow us to start developing a nicer Swift API, and move objc compatibility into its own library for Charts 4.

**Comment by dstranz** [comment]
@jjatie I've just add `NSCopying` conformance to base classes to have compiler validation & change method names.

**Comment by liuxuan30** [comment]
I can't believe how `func copyWithZone(_:) -> AnyObject` is added, lol

**Pull request merged**
