### PR TITLE
 axis named

### PR DESCRIPTION
**Pull request by thierryH91200**
I can't merge on 4.0
sorry

otherwise no problem

capture d ecran 2018-01-11 20 11 19

capture d ecran 2018-01-11 20 09 54

capture d ecran 2018-01-11 20 07 09

capture d ecran 2018-01-11 20 06 16

### CODE REVIEW

**Comment by thierryH91200** [comment]
how use

 xAxis.nameAxis = "Name xAxis"
 xAxis.nameAxisEnabled = true

xAxis.nameAxisFont = NSUIFont.systemFont(ofSize: 14.0) (optionnel)
and text color = same than xAxis.labelTextColor = NSUIColor.red

**Comment by jjatie** [comment]
You need to pull the 4.0.0 branch so it can be merged.

**Comment by thierryH91200** [comment]
no I can't 


capture d ecran 2018-01-12 10 19 42

**Comment by jjatie** [comment]
@thierryH91200 I'm not sure what the image your showing is for. You need to run `git pull upstream 4.0.0` where `upstream` is whatever you called the remote for this repo.

**Comment by jjatie** [comment]
Branch was deleted. Feel free to resubmit @thierryH91200

**Comment by thierryH91200** [comment]
I do not have much time but this weekend it will be possible

**Pull request closed without merging**
