### PR TITLE
Added drawGridLinesOnTopEnabled boolean flag to draw grid lines on top of Bar Charts

### PR DESCRIPTION
**Pull request by JacopoMangiavacchi**
I had this UI requirements for a projects and added this boolean flag, and relative behaviour, to draw the grid lines above the Bar Charts

### CODE REVIEW

**Comment by liuxuan30** [comment]
What's this for? I don't understand. Any screenshot to demonstrate?  From the code I don't see the difference for grid line in front or background?

**Comment by JacopoMangiavacchi** [comment]
Sure thing @liuxuan30 , an image is better than 1000 words ;-)

grid line on top

**Comment by liuxuan30** [comment]
😂 however I can't see the grid line difference?

**Comment by JacopoMangiavacchi** [comment]
Oh, maybe there's another way but I didn't found an existing settings for having the (white) vertical lines draw on top of the (blue/orange) horizontal lines like in the picture above. I just added this setting and in the draw() method I moved the drawing of these lines after the bar lines if this property is true.

**Comment by liuxuan30** [comment]
I just don't see any grid line in your screenshot. And have no idea what's front and behind, since grid line postion and the `contentRect` should not have intersect. That's why I am asking.

**Comment by JacopoMangiavacchi** [comment]
Yes @liuxuan30 . I'm not a designer but as said I just had this UX request to implement a chart like this, with bars cutted off in small rect by the grid line. Other charts frameworks have this feature but I preferred to use Charts so I've implemented this.

**Comment by JacopoMangiavacchi** [comment]
Btw, of course this is just a new optional configuration parameter (drawGridLinesOnTopEnabled) where the default value (false) draw a  traditional chart with grid lines below the bar line.

**Comment by liuxuan30** [comment]
Sure, I see. I will leave this PR to @danielgindi , as I'm not sure if we should add this. I am fine, but adding more 'switches' also needs to be careful

**Comment by jjatie** [comment]
Grid lines should be behind the data. If this is a requirement for your project, that's fine, but it's not something for the shared framework.

**Pull request closed without merging**
