### PR TITLE
simple first line drawing for xAxis added

### PR DESCRIPTION
**Pull request by nikburnt**
now drawFirstLineEnabled available at xAxis for configure to draw or
not to draw

### CODE REVIEW

**Comment by danielgindi** [comment]
Why the code redundancy?

**Comment by kwosu87** [comment]
@danielgindi I really need this feature (especially first grid line for Y Axis in the situation that distinct zero line with '0' label is needed), and I have't figure out how I can handle this one with version 3.0.0.

Is there any feature already on this?

**Comment by kwosu87** [comment]
I handled this situation with child class of `YAxisRenderer` overriding `renderGridLines()` only. However I don't think it is the best solution, maybe it'll be good if there is a little option for this.

**Comment by liuxuan30** [comment]
@jjatie what's the reason to close this?

**Comment by jjatie** [comment]
Too much time went by without activity. The author is free to reopen the PR when they are able to make the changes are rebase to 4.0.0

**Pull request closed without merging**
