### PR TITLE
IBDesignable crash because of Animator

### PR DESCRIPTION
**Pull request by lunalugo25**
I create a subclass of LineChartView and this subclass is loaded in a IBDesignable UIView (CustomView), so when I add a UIView on a StoryBoard and subclass from my CustomView it crash because it's not capable to create '_displayLink'.

### CODE REVIEW

**Comment by liuxuan30** [comment]
well, are you saying it's about swift 2.3 issue? I saw you want to merge into 2.3, but I'm not sure which part the issue resides on

**Comment by danielgindi** [comment]
This PR does not really describe what the changes are, and it contains various commits - not by the author of the PR.
If you want to create a PR, please create one against the latest `master`, with clean and clear code...

**Comment by danielgindi** [comment]
Oh I think I get it

**Comment by lunalugo25** [comment]
Yes, danielgindib that was the issue

**Pull request closed without merging**
