### PR TITLE
Fixes index out of range crash.

### PR DESCRIPTION
**Pull request by kzaher**
This crashed in prod for us.

### CODE REVIEW

**Comment by petester42** [comment]
Thanks. The failing ci is because realm is taking too long to build. I'll merge this.

**Comment by danielgindi** [comment]
Actually, the docs of this function says very clearly that it throws an exception if out of bounds. Why did you run into this in the first place? The caller code should check the bounds

**Comment by kzaher** [comment]
@danielgindi Swift throwing mechanism is different then Java's.

If this was intended behavior, then the prototype should have been:

```
open override func entryForIndex(_ i: Int) throws -> ChartDataEntry
```

or if you wanted fatal error:

```
open override func entryForIndex(_ i: Int) -> ChartDataEntry
```

screen shot 2017-02-22 at 21 06 00

**Comment by danielgindi** [comment]
Yes, I agree that it should be declared as `throws`.

But I'm trying here to understand the situation, not the syntax...
How did you end up getting a fatal error? Did you manually call the function with an invalid argument, updated the chart with invalid data, or did the chart fail and did something wrong?

**Comment by nikwest** [comment]
I ran into the same problem. I created an empty LineChartDataSet. This will crash once the view is displayed.
It might be the problem that 
stride(from:through:by:)
should be replaced by 
stride(from:to:by:)
in LineChartRenderer -> drawLinear(..) Line 332
(just a guess)

**Pull request merged**
