### PR TITLE
added ability to set the label in a BarChartDataEntry

### PR DESCRIPTION
**Pull request by 128keaton**
helpful for if you want to scale your bar to go along with your line chart better.

e.g:
`BarChartDataEntry(value: self.array[i] + 100, xIndex: i, label: formatter.stringFromNumber(self.array[i]))`

### CODE REVIEW

**Comment by 128keaton** [comment]
its a directory issue not related to my code

**Comment by liuxuan30** [comment]
first of all, please fix some code style issues, like addtional lines, spaces, everything that's not related to this PR (adding label for bar chart)
Please also squash your commits - you got 7 commits, and most of them seems irrelevant, e.g. getSnapshot(), pod

**Comment by 128keaton** [comment]
@liuxuan30 ok, I'll work on this ASAP

**Comment by danielgindi** [comment]
Hi!
* It's not really clear what this PR does
* There are 36 files affected in this PR, without any order. And for a quick read - it seems like a repeat of many lines of code
* There are even a pod file change in the PR. This PR is clearly not about releasing a version, so it's clear that it does not belong here

I think that you squashed your commits before rebasing or anything, so you'll need to rebase to clean this up. It will probably not introduce any conflict, just remove the extraneous line codes.

**Comment by 128keaton** [comment]
@danielgindi ok, sounds good :)

**Pull request closed without merging**
